// Code generated by Kitex v0.16.1. DO NOT EDIT.

package verificationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	verification_service "stablepay/api-gateway/kitex_gen/stablepay/verification_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VerifyPurchase(ctx context.Context, req *verification_service.VerifyPurchaseRequest, callOptions ...callopt.Option) (r *verification_service.VerifyPurchaseResponse, err error)
	BatchVerifyPurchase(ctx context.Context, req *verification_service.BatchVerifyPurchaseRequest, callOptions ...callopt.Option) (r *verification_service.BatchVerifyPurchaseResponse, err error)
	GetPurchaseProof(ctx context.Context, req *verification_service.GetPurchaseProofRequest, callOptions ...callopt.Option) (r *verification_service.GetPurchaseProofResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVerificationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVerificationServiceClient struct {
	*kClient
}

func (p *kVerificationServiceClient) VerifyPurchase(ctx context.Context, req *verification_service.VerifyPurchaseRequest, callOptions ...callopt.Option) (r *verification_service.VerifyPurchaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyPurchase(ctx, req)
}

func (p *kVerificationServiceClient) BatchVerifyPurchase(ctx context.Context, req *verification_service.BatchVerifyPurchaseRequest, callOptions ...callopt.Option) (r *verification_service.BatchVerifyPurchaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchVerifyPurchase(ctx, req)
}

func (p *kVerificationServiceClient) GetPurchaseProof(ctx context.Context, req *verification_service.GetPurchaseProofRequest, callOptions ...callopt.Option) (r *verification_service.GetPurchaseProofResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPurchaseProof(ctx, req)
}
