// Code generated by Kitex v0.16.2. DO NOT EDIT.
package verificationservice

import (
	server "github.com/cloudwego/kitex/server"
	verification_service "verification-service/kitex_gen/stablepay/verification_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler verification_service.VerificationService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler verification_service.VerificationService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
