// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package verification_service

import (
	"context"
	"fmt"
	"github.com/stablepay/api-gateway/kitex_gen/stablepay/common"
)

type VerifyPurchaseRequest struct {
	Base     *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDid common.DID      `thrift:"skill_did,3" frugal:"3,default,string" json:"skill_did"`
}

func NewVerifyPurchaseRequest() *VerifyPurchaseRequest {
	return &VerifyPurchaseRequest{}
}

func (p *VerifyPurchaseRequest) InitDefault() {
}

var VerifyPurchaseRequest_Base_DEFAULT *common.BaseReq

func (p *VerifyPurchaseRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return VerifyPurchaseRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyPurchaseRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *VerifyPurchaseRequest) GetSkillDid() (v common.DID) {
	return p.SkillDid
}
func (p *VerifyPurchaseRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *VerifyPurchaseRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *VerifyPurchaseRequest) SetSkillDid(val common.DID) {
	p.SkillDid = val
}

func (p *VerifyPurchaseRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyPurchaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyPurchaseRequest(%+v)", *p)
}

var fieldIDToName_VerifyPurchaseRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_did",
}

type VerifyPurchaseResponse struct {
	Base         *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Purchased    bool             `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string          `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId     `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
	AmountMinor  *int64           `thrift:"amount_minor,5,optional" frugal:"5,optional,i64" json:"amount_minor,omitempty"`
	Currency     *common.Currency `thrift:"currency,6,optional" frugal:"6,optional,Currency" json:"currency,omitempty"`
}

func NewVerifyPurchaseResponse() *VerifyPurchaseResponse {
	return &VerifyPurchaseResponse{}
}

func (p *VerifyPurchaseResponse) InitDefault() {
}

var VerifyPurchaseResponse_Base_DEFAULT *common.BaseResp

func (p *VerifyPurchaseResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return VerifyPurchaseResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyPurchaseResponse) GetPurchased() (v bool) {
	return p.Purchased
}

var VerifyPurchaseResponse_PurchaseTime_DEFAULT string

func (p *VerifyPurchaseResponse) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return VerifyPurchaseResponse_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var VerifyPurchaseResponse_TxId_DEFAULT common.TxId

func (p *VerifyPurchaseResponse) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return VerifyPurchaseResponse_TxId_DEFAULT
	}
	return *p.TxId
}

var VerifyPurchaseResponse_AmountMinor_DEFAULT int64

func (p *VerifyPurchaseResponse) GetAmountMinor() (v int64) {
	if !p.IsSetAmountMinor() {
		return VerifyPurchaseResponse_AmountMinor_DEFAULT
	}
	return *p.AmountMinor
}

var VerifyPurchaseResponse_Currency_DEFAULT common.Currency

func (p *VerifyPurchaseResponse) GetCurrency() (v common.Currency) {
	if !p.IsSetCurrency() {
		return VerifyPurchaseResponse_Currency_DEFAULT
	}
	return *p.Currency
}
func (p *VerifyPurchaseResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *VerifyPurchaseResponse) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *VerifyPurchaseResponse) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *VerifyPurchaseResponse) SetTxId(val *common.TxId) {
	p.TxId = val
}
func (p *VerifyPurchaseResponse) SetAmountMinor(val *int64) {
	p.AmountMinor = val
}
func (p *VerifyPurchaseResponse) SetCurrency(val *common.Currency) {
	p.Currency = val
}

func (p *VerifyPurchaseResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyPurchaseResponse) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *VerifyPurchaseResponse) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *VerifyPurchaseResponse) IsSetAmountMinor() bool {
	return p.AmountMinor != nil
}

func (p *VerifyPurchaseResponse) IsSetCurrency() bool {
	return p.Currency != nil
}

func (p *VerifyPurchaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyPurchaseResponse(%+v)", *p)
}

var fieldIDToName_VerifyPurchaseResponse = map[int16]string{
	1: "base",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
	5: "amount_minor",
	6: "currency",
}

type BatchVerifyItem struct {
	SkillDid     common.DID   `thrift:"skill_did,1" frugal:"1,default,string" json:"skill_did"`
	Purchased    bool         `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string      `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
}

func NewBatchVerifyItem() *BatchVerifyItem {
	return &BatchVerifyItem{}
}

func (p *BatchVerifyItem) InitDefault() {
}

func (p *BatchVerifyItem) GetSkillDid() (v common.DID) {
	return p.SkillDid
}

func (p *BatchVerifyItem) GetPurchased() (v bool) {
	return p.Purchased
}

var BatchVerifyItem_PurchaseTime_DEFAULT string

func (p *BatchVerifyItem) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return BatchVerifyItem_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var BatchVerifyItem_TxId_DEFAULT common.TxId

func (p *BatchVerifyItem) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return BatchVerifyItem_TxId_DEFAULT
	}
	return *p.TxId
}
func (p *BatchVerifyItem) SetSkillDid(val common.DID) {
	p.SkillDid = val
}
func (p *BatchVerifyItem) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *BatchVerifyItem) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *BatchVerifyItem) SetTxId(val *common.TxId) {
	p.TxId = val
}

func (p *BatchVerifyItem) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *BatchVerifyItem) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *BatchVerifyItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyItem(%+v)", *p)
}

var fieldIDToName_BatchVerifyItem = map[int16]string{
	1: "skill_did",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
}

type BatchVerifyPurchaseRequest struct {
	Base      *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid  common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDids []common.DID    `thrift:"skill_dids,3" frugal:"3,default,list<string>" json:"skill_dids"`
}

func NewBatchVerifyPurchaseRequest() *BatchVerifyPurchaseRequest {
	return &BatchVerifyPurchaseRequest{}
}

func (p *BatchVerifyPurchaseRequest) InitDefault() {
}

var BatchVerifyPurchaseRequest_Base_DEFAULT *common.BaseReq

func (p *BatchVerifyPurchaseRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return BatchVerifyPurchaseRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *BatchVerifyPurchaseRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *BatchVerifyPurchaseRequest) GetSkillDids() (v []common.DID) {
	return p.SkillDids
}
func (p *BatchVerifyPurchaseRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *BatchVerifyPurchaseRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *BatchVerifyPurchaseRequest) SetSkillDids(val []common.DID) {
	p.SkillDids = val
}

func (p *BatchVerifyPurchaseRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchVerifyPurchaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyPurchaseRequest(%+v)", *p)
}

var fieldIDToName_BatchVerifyPurchaseRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_dids",
}

type BatchVerifyPurchaseResponse struct {
	Base  *common.BaseResp   `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Items []*BatchVerifyItem `thrift:"items,2" frugal:"2,default,list<BatchVerifyItem>" json:"items"`
}

func NewBatchVerifyPurchaseResponse() *BatchVerifyPurchaseResponse {
	return &BatchVerifyPurchaseResponse{}
}

func (p *BatchVerifyPurchaseResponse) InitDefault() {
}

var BatchVerifyPurchaseResponse_Base_DEFAULT *common.BaseResp

func (p *BatchVerifyPurchaseResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return BatchVerifyPurchaseResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *BatchVerifyPurchaseResponse) GetItems() (v []*BatchVerifyItem) {
	return p.Items
}
func (p *BatchVerifyPurchaseResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *BatchVerifyPurchaseResponse) SetItems(val []*BatchVerifyItem) {
	p.Items = val
}

func (p *BatchVerifyPurchaseResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchVerifyPurchaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyPurchaseResponse(%+v)", *p)
}

var fieldIDToName_BatchVerifyPurchaseResponse = map[int16]string{
	1: "base",
	2: "items",
}

type GetPurchaseProofRequest struct {
	Base     *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDid common.DID      `thrift:"skill_did,3" frugal:"3,default,string" json:"skill_did"`
}

func NewGetPurchaseProofRequest() *GetPurchaseProofRequest {
	return &GetPurchaseProofRequest{}
}

func (p *GetPurchaseProofRequest) InitDefault() {
}

var GetPurchaseProofRequest_Base_DEFAULT *common.BaseReq

func (p *GetPurchaseProofRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetPurchaseProofRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPurchaseProofRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *GetPurchaseProofRequest) GetSkillDid() (v common.DID) {
	return p.SkillDid
}
func (p *GetPurchaseProofRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetPurchaseProofRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *GetPurchaseProofRequest) SetSkillDid(val common.DID) {
	p.SkillDid = val
}

func (p *GetPurchaseProofRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPurchaseProofRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPurchaseProofRequest(%+v)", *p)
}

var fieldIDToName_GetPurchaseProofRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_did",
}

type GetPurchaseProofResponse struct {
	Base         *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Purchased    bool             `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string          `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId     `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
	AmountMinor  *int64           `thrift:"amount_minor,5,optional" frugal:"5,optional,i64" json:"amount_minor,omitempty"`
	Currency     *common.Currency `thrift:"currency,6,optional" frugal:"6,optional,Currency" json:"currency,omitempty"`
	TxHash       *common.TxHash   `thrift:"tx_hash,7,optional" frugal:"7,optional,string" json:"tx_hash,omitempty"`
	ProofVersion *string          `thrift:"proof_version,8,optional" frugal:"8,optional,string" json:"proof_version,omitempty"`
}

func NewGetPurchaseProofResponse() *GetPurchaseProofResponse {
	return &GetPurchaseProofResponse{}
}

func (p *GetPurchaseProofResponse) InitDefault() {
}

var GetPurchaseProofResponse_Base_DEFAULT *common.BaseResp

func (p *GetPurchaseProofResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetPurchaseProofResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPurchaseProofResponse) GetPurchased() (v bool) {
	return p.Purchased
}

var GetPurchaseProofResponse_PurchaseTime_DEFAULT string

func (p *GetPurchaseProofResponse) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return GetPurchaseProofResponse_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var GetPurchaseProofResponse_TxId_DEFAULT common.TxId

func (p *GetPurchaseProofResponse) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return GetPurchaseProofResponse_TxId_DEFAULT
	}
	return *p.TxId
}

var GetPurchaseProofResponse_AmountMinor_DEFAULT int64

func (p *GetPurchaseProofResponse) GetAmountMinor() (v int64) {
	if !p.IsSetAmountMinor() {
		return GetPurchaseProofResponse_AmountMinor_DEFAULT
	}
	return *p.AmountMinor
}

var GetPurchaseProofResponse_Currency_DEFAULT common.Currency

func (p *GetPurchaseProofResponse) GetCurrency() (v common.Currency) {
	if !p.IsSetCurrency() {
		return GetPurchaseProofResponse_Currency_DEFAULT
	}
	return *p.Currency
}

var GetPurchaseProofResponse_TxHash_DEFAULT common.TxHash

func (p *GetPurchaseProofResponse) GetTxHash() (v common.TxHash) {
	if !p.IsSetTxHash() {
		return GetPurchaseProofResponse_TxHash_DEFAULT
	}
	return *p.TxHash
}

var GetPurchaseProofResponse_ProofVersion_DEFAULT string

func (p *GetPurchaseProofResponse) GetProofVersion() (v string) {
	if !p.IsSetProofVersion() {
		return GetPurchaseProofResponse_ProofVersion_DEFAULT
	}
	return *p.ProofVersion
}
func (p *GetPurchaseProofResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetPurchaseProofResponse) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *GetPurchaseProofResponse) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *GetPurchaseProofResponse) SetTxId(val *common.TxId) {
	p.TxId = val
}
func (p *GetPurchaseProofResponse) SetAmountMinor(val *int64) {
	p.AmountMinor = val
}
func (p *GetPurchaseProofResponse) SetCurrency(val *common.Currency) {
	p.Currency = val
}
func (p *GetPurchaseProofResponse) SetTxHash(val *common.TxHash) {
	p.TxHash = val
}
func (p *GetPurchaseProofResponse) SetProofVersion(val *string) {
	p.ProofVersion = val
}

func (p *GetPurchaseProofResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPurchaseProofResponse) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *GetPurchaseProofResponse) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *GetPurchaseProofResponse) IsSetAmountMinor() bool {
	return p.AmountMinor != nil
}

func (p *GetPurchaseProofResponse) IsSetCurrency() bool {
	return p.Currency != nil
}

func (p *GetPurchaseProofResponse) IsSetTxHash() bool {
	return p.TxHash != nil
}

func (p *GetPurchaseProofResponse) IsSetProofVersion() bool {
	return p.ProofVersion != nil
}

func (p *GetPurchaseProofResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPurchaseProofResponse(%+v)", *p)
}

var fieldIDToName_GetPurchaseProofResponse = map[int16]string{
	1: "base",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
	5: "amount_minor",
	6: "currency",
	7: "tx_hash",
	8: "proof_version",
}

type VerificationService interface {
	VerifyPurchase(ctx context.Context, req *VerifyPurchaseRequest) (r *VerifyPurchaseResponse, err error)

	BatchVerifyPurchase(ctx context.Context, req *BatchVerifyPurchaseRequest) (r *BatchVerifyPurchaseResponse, err error)

	GetPurchaseProof(ctx context.Context, req *GetPurchaseProofRequest) (r *GetPurchaseProofResponse, err error)
}

type VerificationServiceVerifyPurchaseArgs struct {
	Req *VerifyPurchaseRequest `thrift:"req,1" frugal:"1,default,VerifyPurchaseRequest" json:"req"`
}

func NewVerificationServiceVerifyPurchaseArgs() *VerificationServiceVerifyPurchaseArgs {
	return &VerificationServiceVerifyPurchaseArgs{}
}

func (p *VerificationServiceVerifyPurchaseArgs) InitDefault() {
}

var VerificationServiceVerifyPurchaseArgs_Req_DEFAULT *VerifyPurchaseRequest

func (p *VerificationServiceVerifyPurchaseArgs) GetReq() (v *VerifyPurchaseRequest) {
	if !p.IsSetReq() {
		return VerificationServiceVerifyPurchaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceVerifyPurchaseArgs) SetReq(val *VerifyPurchaseRequest) {
	p.Req = val
}

func (p *VerificationServiceVerifyPurchaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceVerifyPurchaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyPurchaseArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyPurchaseArgs = map[int16]string{
	1: "req",
}

type VerificationServiceVerifyPurchaseResult struct {
	Success *VerifyPurchaseResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyPurchaseResponse" json:"success,omitempty"`
}

func NewVerificationServiceVerifyPurchaseResult() *VerificationServiceVerifyPurchaseResult {
	return &VerificationServiceVerifyPurchaseResult{}
}

func (p *VerificationServiceVerifyPurchaseResult) InitDefault() {
}

var VerificationServiceVerifyPurchaseResult_Success_DEFAULT *VerifyPurchaseResponse

func (p *VerificationServiceVerifyPurchaseResult) GetSuccess() (v *VerifyPurchaseResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceVerifyPurchaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceVerifyPurchaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyPurchaseResponse)
}

func (p *VerificationServiceVerifyPurchaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceVerifyPurchaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyPurchaseResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyPurchaseResult = map[int16]string{
	0: "success",
}

type VerificationServiceBatchVerifyPurchaseArgs struct {
	Req *BatchVerifyPurchaseRequest `thrift:"req,1" frugal:"1,default,BatchVerifyPurchaseRequest" json:"req"`
}

func NewVerificationServiceBatchVerifyPurchaseArgs() *VerificationServiceBatchVerifyPurchaseArgs {
	return &VerificationServiceBatchVerifyPurchaseArgs{}
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) InitDefault() {
}

var VerificationServiceBatchVerifyPurchaseArgs_Req_DEFAULT *BatchVerifyPurchaseRequest

func (p *VerificationServiceBatchVerifyPurchaseArgs) GetReq() (v *BatchVerifyPurchaseRequest) {
	if !p.IsSetReq() {
		return VerificationServiceBatchVerifyPurchaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceBatchVerifyPurchaseArgs) SetReq(val *BatchVerifyPurchaseRequest) {
	p.Req = val
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceBatchVerifyPurchaseArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceBatchVerifyPurchaseArgs = map[int16]string{
	1: "req",
}

type VerificationServiceBatchVerifyPurchaseResult struct {
	Success *BatchVerifyPurchaseResponse `thrift:"success,0,optional" frugal:"0,optional,BatchVerifyPurchaseResponse" json:"success,omitempty"`
}

func NewVerificationServiceBatchVerifyPurchaseResult() *VerificationServiceBatchVerifyPurchaseResult {
	return &VerificationServiceBatchVerifyPurchaseResult{}
}

func (p *VerificationServiceBatchVerifyPurchaseResult) InitDefault() {
}

var VerificationServiceBatchVerifyPurchaseResult_Success_DEFAULT *BatchVerifyPurchaseResponse

func (p *VerificationServiceBatchVerifyPurchaseResult) GetSuccess() (v *BatchVerifyPurchaseResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceBatchVerifyPurchaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceBatchVerifyPurchaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchVerifyPurchaseResponse)
}

func (p *VerificationServiceBatchVerifyPurchaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceBatchVerifyPurchaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceBatchVerifyPurchaseResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceBatchVerifyPurchaseResult = map[int16]string{
	0: "success",
}

type VerificationServiceGetPurchaseProofArgs struct {
	Req *GetPurchaseProofRequest `thrift:"req,1" frugal:"1,default,GetPurchaseProofRequest" json:"req"`
}

func NewVerificationServiceGetPurchaseProofArgs() *VerificationServiceGetPurchaseProofArgs {
	return &VerificationServiceGetPurchaseProofArgs{}
}

func (p *VerificationServiceGetPurchaseProofArgs) InitDefault() {
}

var VerificationServiceGetPurchaseProofArgs_Req_DEFAULT *GetPurchaseProofRequest

func (p *VerificationServiceGetPurchaseProofArgs) GetReq() (v *GetPurchaseProofRequest) {
	if !p.IsSetReq() {
		return VerificationServiceGetPurchaseProofArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceGetPurchaseProofArgs) SetReq(val *GetPurchaseProofRequest) {
	p.Req = val
}

func (p *VerificationServiceGetPurchaseProofArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceGetPurchaseProofArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetPurchaseProofArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetPurchaseProofArgs = map[int16]string{
	1: "req",
}

type VerificationServiceGetPurchaseProofResult struct {
	Success *GetPurchaseProofResponse `thrift:"success,0,optional" frugal:"0,optional,GetPurchaseProofResponse" json:"success,omitempty"`
}

func NewVerificationServiceGetPurchaseProofResult() *VerificationServiceGetPurchaseProofResult {
	return &VerificationServiceGetPurchaseProofResult{}
}

func (p *VerificationServiceGetPurchaseProofResult) InitDefault() {
}

var VerificationServiceGetPurchaseProofResult_Success_DEFAULT *GetPurchaseProofResponse

func (p *VerificationServiceGetPurchaseProofResult) GetSuccess() (v *GetPurchaseProofResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceGetPurchaseProofResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceGetPurchaseProofResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPurchaseProofResponse)
}

func (p *VerificationServiceGetPurchaseProofResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceGetPurchaseProofResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetPurchaseProofResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetPurchaseProofResult = map[int16]string{
	0: "success",
}
