apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-query-service
  namespace: stablepay-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stablepay-query-service
  template:
    metadata:
      labels:
        app: stablepay-query-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: query-service
          image: stablepay-registry.cn-shanghai.cr.aliyuncs.com/stablepay-dev/query-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: stablepay-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: stablepay-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stablepay-secrets
                  key: mysql-password
            - name: MYSQL_DBNAME
              value: stablepay_query_db
          ports:
            - containerPort: 8084
              name: rpc
            - containerPort: 8184
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: stablepay-query-service
  namespace: stablepay-dev
spec:
  selector:
    app: stablepay-query-service
  ports:
    - name: rpc
      port: 8084
      targetPort: 8084
    - name: http
      port: 8184
      targetPort: 8184
