// Code generated by Kitex v0.16.1. DO NOT EDIT.

package didservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	did_service "stablepay/api-gateway/kitex_gen/stablepay/did_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateDID": kitex.NewMethodInfo(
		createDIDHandler,
		newDIDServiceCreateDIDArgs,
		newDIDServiceCreateDIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDID": kitex.NewMethodInfo(
		getDIDHandler,
		newDIDServiceGetDIDArgs,
		newDIDServiceGetDIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifySignature": kitex.NewMethodInfo(
		verifySignatureHandler,
		newDIDServiceVerifySignatureArgs,
		newDIDServiceVerifySignatureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDIDConfig": kitex.NewMethodInfo(
		updateDIDConfigHandler,
		newDIDServiceUpdateDIDConfigArgs,
		newDIDServiceUpdateDIDConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	dIDServiceServiceInfo                = NewServiceInfo()
	dIDServiceServiceInfoForClient       = NewServiceInfoForClient()
	dIDServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return dIDServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return dIDServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return dIDServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DIDService"
	handlerType := (*did_service.DIDService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "did_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createDIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*did_service.DIDServiceCreateDIDArgs)
	realResult := result.(*did_service.DIDServiceCreateDIDResult)
	success, err := handler.(did_service.DIDService).CreateDID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDIDServiceCreateDIDArgs() interface{} {
	return did_service.NewDIDServiceCreateDIDArgs()
}

func newDIDServiceCreateDIDResult() interface{} {
	return did_service.NewDIDServiceCreateDIDResult()
}

func getDIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*did_service.DIDServiceGetDIDArgs)
	realResult := result.(*did_service.DIDServiceGetDIDResult)
	success, err := handler.(did_service.DIDService).GetDID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDIDServiceGetDIDArgs() interface{} {
	return did_service.NewDIDServiceGetDIDArgs()
}

func newDIDServiceGetDIDResult() interface{} {
	return did_service.NewDIDServiceGetDIDResult()
}

func verifySignatureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*did_service.DIDServiceVerifySignatureArgs)
	realResult := result.(*did_service.DIDServiceVerifySignatureResult)
	success, err := handler.(did_service.DIDService).VerifySignature(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDIDServiceVerifySignatureArgs() interface{} {
	return did_service.NewDIDServiceVerifySignatureArgs()
}

func newDIDServiceVerifySignatureResult() interface{} {
	return did_service.NewDIDServiceVerifySignatureResult()
}

func updateDIDConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*did_service.DIDServiceUpdateDIDConfigArgs)
	realResult := result.(*did_service.DIDServiceUpdateDIDConfigResult)
	success, err := handler.(did_service.DIDService).UpdateDIDConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDIDServiceUpdateDIDConfigArgs() interface{} {
	return did_service.NewDIDServiceUpdateDIDConfigArgs()
}

func newDIDServiceUpdateDIDConfigResult() interface{} {
	return did_service.NewDIDServiceUpdateDIDConfigResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateDID(ctx context.Context, req *did_service.CreateDIDRequest) (r *did_service.CreateDIDResponse, err error) {
	var _args did_service.DIDServiceCreateDIDArgs
	_args.Req = req
	var _result did_service.DIDServiceCreateDIDResult
	if err = p.c.Call(ctx, "CreateDID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDID(ctx context.Context, req *did_service.GetDIDRequest) (r *did_service.GetDIDResponse, err error) {
	var _args did_service.DIDServiceGetDIDArgs
	_args.Req = req
	var _result did_service.DIDServiceGetDIDResult
	if err = p.c.Call(ctx, "GetDID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifySignature(ctx context.Context, req *did_service.VerifySignatureRequest) (r *did_service.VerifySignatureResponse, err error) {
	var _args did_service.DIDServiceVerifySignatureArgs
	_args.Req = req
	var _result did_service.DIDServiceVerifySignatureResult
	if err = p.c.Call(ctx, "VerifySignature", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDIDConfig(ctx context.Context, req *did_service.UpdateDIDConfigRequest) (r *did_service.UpdateDIDConfigResponse, err error) {
	var _args did_service.DIDServiceUpdateDIDConfigArgs
	_args.Req = req
	var _result did_service.DIDServiceUpdateDIDConfigResult
	if err = p.c.Call(ctx, "UpdateDIDConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
