// Code generated by Kitex v0.16.1. DO NOT EDIT.
package didservice

import (
	server "github.com/cloudwego/kitex/server"
	did_service "stablepay/api-gateway/kitex_gen/stablepay/did_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler did_service.DIDService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler did_service.DIDService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
