## RocketMQ Broker 最小配置（建议不要写死 brokerIP1，让 broker 在容器网络内自适应）
## 参考 apache/rocketmq:5.3.2 默认 broker.conf

brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

deleteWhen = 04
fileReservedTime = 48

# nameserver 地址（容器内）
namesrvAddr = rocketmq-nameserver:9876

# 建议开启，减少手工创建 topic 的需求
autoCreateTopicEnable = true