// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package did_service

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"stablepay/api-gateway/kitex_gen/stablepay/common"
)

type UserType int64

const (
	UserType_AGENT     UserType = 1
	UserType_DEVELOPER UserType = 2
)

func (p UserType) String() string {
	switch p {
	case UserType_AGENT:
		return "AGENT"
	case UserType_DEVELOPER:
		return "DEVELOPER"
	}
	return "<UNSET>"
}

func UserTypeFromString(s string) (UserType, error) {
	switch s {
	case "AGENT":
		return UserType_AGENT, nil
	case "DEVELOPER":
		return UserType_DEVELOPER, nil
	}
	return UserType(0), fmt.Errorf("not a valid UserType string")
}

func UserTypePtr(v UserType) *UserType { return &v }
func (p *UserType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserType(result.Int64)
	return
}

func (p *UserType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CreateDIDRequest struct {
	Base     *common.BaseReq   `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	UserType UserType          `thrift:"user_type,2" frugal:"2,default,UserType" json:"user_type"`
	Metadata map[string]string `thrift:"metadata,3,optional" frugal:"3,optional,map<string:string>" json:"metadata,omitempty"`
}

func NewCreateDIDRequest() *CreateDIDRequest {
	return &CreateDIDRequest{}
}

func (p *CreateDIDRequest) InitDefault() {
}

var CreateDIDRequest_Base_DEFAULT *common.BaseReq

func (p *CreateDIDRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return CreateDIDRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *CreateDIDRequest) GetUserType() (v UserType) {
	return p.UserType
}

var CreateDIDRequest_Metadata_DEFAULT map[string]string

func (p *CreateDIDRequest) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return CreateDIDRequest_Metadata_DEFAULT
	}
	return p.Metadata
}
func (p *CreateDIDRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *CreateDIDRequest) SetUserType(val UserType) {
	p.UserType = val
}
func (p *CreateDIDRequest) SetMetadata(val map[string]string) {
	p.Metadata = val
}

func (p *CreateDIDRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateDIDRequest) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *CreateDIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateDIDRequest(%+v)", *p)
}

var fieldIDToName_CreateDIDRequest = map[int16]string{
	1: "base",
	2: "user_type",
	3: "metadata",
}

type CreateDIDResponse struct {
	Base          *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Did           common.DID       `thrift:"did,2" frugal:"2,default,string" json:"did"`
	PublicKey     string           `thrift:"public_key,3" frugal:"3,default,string" json:"public_key"`
	WalletAddress string           `thrift:"wallet_address,4" frugal:"4,default,string" json:"wallet_address"`
	CreatedAt     string           `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
}

func NewCreateDIDResponse() *CreateDIDResponse {
	return &CreateDIDResponse{}
}

func (p *CreateDIDResponse) InitDefault() {
}

var CreateDIDResponse_Base_DEFAULT *common.BaseResp

func (p *CreateDIDResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return CreateDIDResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *CreateDIDResponse) GetDid() (v common.DID) {
	return p.Did
}

func (p *CreateDIDResponse) GetPublicKey() (v string) {
	return p.PublicKey
}

func (p *CreateDIDResponse) GetWalletAddress() (v string) {
	return p.WalletAddress
}

func (p *CreateDIDResponse) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *CreateDIDResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *CreateDIDResponse) SetDid(val common.DID) {
	p.Did = val
}
func (p *CreateDIDResponse) SetPublicKey(val string) {
	p.PublicKey = val
}
func (p *CreateDIDResponse) SetWalletAddress(val string) {
	p.WalletAddress = val
}
func (p *CreateDIDResponse) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *CreateDIDResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateDIDResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateDIDResponse(%+v)", *p)
}

var fieldIDToName_CreateDIDResponse = map[int16]string{
	1: "base",
	2: "did",
	3: "public_key",
	4: "wallet_address",
	5: "created_at",
}

type RegisterDIDRequest struct {
	Base          *common.BaseReq   `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	UserType      UserType          `thrift:"user_type,2" frugal:"2,default,UserType" json:"user_type"`
	PublicKey     string            `thrift:"public_key,3" frugal:"3,default,string" json:"public_key"`
	WalletAddress string            `thrift:"wallet_address,4" frugal:"4,default,string" json:"wallet_address"`
	WalletId      string            `thrift:"wallet_id,5" frugal:"5,default,string" json:"wallet_id"`
	WalletName    string            `thrift:"wallet_name,6" frugal:"6,default,string" json:"wallet_name"`
	Metadata      map[string]string `thrift:"metadata,7,optional" frugal:"7,optional,map<string:string>" json:"metadata,omitempty"`
}

func NewRegisterDIDRequest() *RegisterDIDRequest {
	return &RegisterDIDRequest{}
}

func (p *RegisterDIDRequest) InitDefault() {
}

var RegisterDIDRequest_Base_DEFAULT *common.BaseReq

func (p *RegisterDIDRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return RegisterDIDRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *RegisterDIDRequest) GetUserType() (v UserType) {
	return p.UserType
}

func (p *RegisterDIDRequest) GetPublicKey() (v string) {
	return p.PublicKey
}

func (p *RegisterDIDRequest) GetWalletAddress() (v string) {
	return p.WalletAddress
}

func (p *RegisterDIDRequest) GetWalletId() (v string) {
	return p.WalletId
}

func (p *RegisterDIDRequest) GetWalletName() (v string) {
	return p.WalletName
}

var RegisterDIDRequest_Metadata_DEFAULT map[string]string

func (p *RegisterDIDRequest) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return RegisterDIDRequest_Metadata_DEFAULT
	}
	return p.Metadata
}
func (p *RegisterDIDRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *RegisterDIDRequest) SetUserType(val UserType) {
	p.UserType = val
}
func (p *RegisterDIDRequest) SetPublicKey(val string) {
	p.PublicKey = val
}
func (p *RegisterDIDRequest) SetWalletAddress(val string) {
	p.WalletAddress = val
}
func (p *RegisterDIDRequest) SetWalletId(val string) {
	p.WalletId = val
}
func (p *RegisterDIDRequest) SetWalletName(val string) {
	p.WalletName = val
}
func (p *RegisterDIDRequest) SetMetadata(val map[string]string) {
	p.Metadata = val
}

func (p *RegisterDIDRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterDIDRequest) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *RegisterDIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterDIDRequest(%+v)", *p)
}

var fieldIDToName_RegisterDIDRequest = map[int16]string{
	1: "base",
	2: "user_type",
	3: "public_key",
	4: "wallet_address",
	5: "wallet_id",
	6: "wallet_name",
	7: "metadata",
}

type RegisterDIDResponse struct {
	Base          *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Did           common.DID       `thrift:"did,2" frugal:"2,default,string" json:"did"`
	PublicKey     string           `thrift:"public_key,3" frugal:"3,default,string" json:"public_key"`
	WalletAddress string           `thrift:"wallet_address,4" frugal:"4,default,string" json:"wallet_address"`
	CreatedAt     string           `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
}

func NewRegisterDIDResponse() *RegisterDIDResponse {
	return &RegisterDIDResponse{}
}

func (p *RegisterDIDResponse) InitDefault() {
}

var RegisterDIDResponse_Base_DEFAULT *common.BaseResp

func (p *RegisterDIDResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return RegisterDIDResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *RegisterDIDResponse) GetDid() (v common.DID) {
	return p.Did
}

func (p *RegisterDIDResponse) GetPublicKey() (v string) {
	return p.PublicKey
}

func (p *RegisterDIDResponse) GetWalletAddress() (v string) {
	return p.WalletAddress
}

func (p *RegisterDIDResponse) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *RegisterDIDResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *RegisterDIDResponse) SetDid(val common.DID) {
	p.Did = val
}
func (p *RegisterDIDResponse) SetPublicKey(val string) {
	p.PublicKey = val
}
func (p *RegisterDIDResponse) SetWalletAddress(val string) {
	p.WalletAddress = val
}
func (p *RegisterDIDResponse) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *RegisterDIDResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterDIDResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterDIDResponse(%+v)", *p)
}

var fieldIDToName_RegisterDIDResponse = map[int16]string{
	1: "base",
	2: "did",
	3: "public_key",
	4: "wallet_address",
	5: "created_at",
}

type GetDIDRequest struct {
	Base *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	Did  common.DID      `thrift:"did,2" frugal:"2,default,string" json:"did"`
}

func NewGetDIDRequest() *GetDIDRequest {
	return &GetDIDRequest{}
}

func (p *GetDIDRequest) InitDefault() {
}

var GetDIDRequest_Base_DEFAULT *common.BaseReq

func (p *GetDIDRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetDIDRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetDIDRequest) GetDid() (v common.DID) {
	return p.Did
}
func (p *GetDIDRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetDIDRequest) SetDid(val common.DID) {
	p.Did = val
}

func (p *GetDIDRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetDIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDIDRequest(%+v)", *p)
}

var fieldIDToName_GetDIDRequest = map[int16]string{
	1: "base",
	2: "did",
}

type GetDIDResponse struct {
	Base          *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Did           common.DID       `thrift:"did,2" frugal:"2,default,string" json:"did"`
	PublicKey     string           `thrift:"public_key,3" frugal:"3,default,string" json:"public_key"`
	WalletAddress string           `thrift:"wallet_address,4" frugal:"4,default,string" json:"wallet_address"`
}

func NewGetDIDResponse() *GetDIDResponse {
	return &GetDIDResponse{}
}

func (p *GetDIDResponse) InitDefault() {
}

var GetDIDResponse_Base_DEFAULT *common.BaseResp

func (p *GetDIDResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetDIDResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetDIDResponse) GetDid() (v common.DID) {
	return p.Did
}

func (p *GetDIDResponse) GetPublicKey() (v string) {
	return p.PublicKey
}

func (p *GetDIDResponse) GetWalletAddress() (v string) {
	return p.WalletAddress
}
func (p *GetDIDResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetDIDResponse) SetDid(val common.DID) {
	p.Did = val
}
func (p *GetDIDResponse) SetPublicKey(val string) {
	p.PublicKey = val
}
func (p *GetDIDResponse) SetWalletAddress(val string) {
	p.WalletAddress = val
}

func (p *GetDIDResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetDIDResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDIDResponse(%+v)", *p)
}

var fieldIDToName_GetDIDResponse = map[int16]string{
	1: "base",
	2: "did",
	3: "public_key",
	4: "wallet_address",
}

type VerifySignatureRequest struct {
	Base      *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	Did       common.DID      `thrift:"did,2" frugal:"2,default,string" json:"did"`
	Message   string          `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Signature string          `thrift:"signature,4" frugal:"4,default,string" json:"signature"`
	Timestamp string          `thrift:"timestamp,5" frugal:"5,default,string" json:"timestamp"`
	Nonce     *string         `thrift:"nonce,6,optional" frugal:"6,optional,string" json:"nonce,omitempty"`
}

func NewVerifySignatureRequest() *VerifySignatureRequest {
	return &VerifySignatureRequest{}
}

func (p *VerifySignatureRequest) InitDefault() {
}

var VerifySignatureRequest_Base_DEFAULT *common.BaseReq

func (p *VerifySignatureRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return VerifySignatureRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifySignatureRequest) GetDid() (v common.DID) {
	return p.Did
}

func (p *VerifySignatureRequest) GetMessage() (v string) {
	return p.Message
}

func (p *VerifySignatureRequest) GetSignature() (v string) {
	return p.Signature
}

func (p *VerifySignatureRequest) GetTimestamp() (v string) {
	return p.Timestamp
}

var VerifySignatureRequest_Nonce_DEFAULT string

func (p *VerifySignatureRequest) GetNonce() (v string) {
	if !p.IsSetNonce() {
		return VerifySignatureRequest_Nonce_DEFAULT
	}
	return *p.Nonce
}
func (p *VerifySignatureRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *VerifySignatureRequest) SetDid(val common.DID) {
	p.Did = val
}
func (p *VerifySignatureRequest) SetMessage(val string) {
	p.Message = val
}
func (p *VerifySignatureRequest) SetSignature(val string) {
	p.Signature = val
}
func (p *VerifySignatureRequest) SetTimestamp(val string) {
	p.Timestamp = val
}
func (p *VerifySignatureRequest) SetNonce(val *string) {
	p.Nonce = val
}

func (p *VerifySignatureRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifySignatureRequest) IsSetNonce() bool {
	return p.Nonce != nil
}

func (p *VerifySignatureRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySignatureRequest(%+v)", *p)
}

var fieldIDToName_VerifySignatureRequest = map[int16]string{
	1: "base",
	2: "did",
	3: "message",
	4: "signature",
	5: "timestamp",
	6: "nonce",
}

type VerifySignatureResponse struct {
	Base  *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Valid bool             `thrift:"valid,2" frugal:"2,default,bool" json:"valid"`
}

func NewVerifySignatureResponse() *VerifySignatureResponse {
	return &VerifySignatureResponse{}
}

func (p *VerifySignatureResponse) InitDefault() {
}

var VerifySignatureResponse_Base_DEFAULT *common.BaseResp

func (p *VerifySignatureResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return VerifySignatureResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifySignatureResponse) GetValid() (v bool) {
	return p.Valid
}
func (p *VerifySignatureResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *VerifySignatureResponse) SetValid(val bool) {
	p.Valid = val
}

func (p *VerifySignatureResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifySignatureResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySignatureResponse(%+v)", *p)
}

var fieldIDToName_VerifySignatureResponse = map[int16]string{
	1: "base",
	2: "valid",
}

type UpdateDIDConfigRequest struct {
	Base          *common.BaseReq   `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	Did           common.DID        `thrift:"did,2" frugal:"2,default,string" json:"did"`
	ConfigVersion *int64            `thrift:"config_version,3,optional" frugal:"3,optional,i64" json:"config_version,omitempty"`
	ConfigKv      map[string]string `thrift:"config_kv,4" frugal:"4,default,map<string:string>" json:"config_kv"`
}

func NewUpdateDIDConfigRequest() *UpdateDIDConfigRequest {
	return &UpdateDIDConfigRequest{}
}

func (p *UpdateDIDConfigRequest) InitDefault() {
}

var UpdateDIDConfigRequest_Base_DEFAULT *common.BaseReq

func (p *UpdateDIDConfigRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return UpdateDIDConfigRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *UpdateDIDConfigRequest) GetDid() (v common.DID) {
	return p.Did
}

var UpdateDIDConfigRequest_ConfigVersion_DEFAULT int64

func (p *UpdateDIDConfigRequest) GetConfigVersion() (v int64) {
	if !p.IsSetConfigVersion() {
		return UpdateDIDConfigRequest_ConfigVersion_DEFAULT
	}
	return *p.ConfigVersion
}

func (p *UpdateDIDConfigRequest) GetConfigKv() (v map[string]string) {
	return p.ConfigKv
}
func (p *UpdateDIDConfigRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *UpdateDIDConfigRequest) SetDid(val common.DID) {
	p.Did = val
}
func (p *UpdateDIDConfigRequest) SetConfigVersion(val *int64) {
	p.ConfigVersion = val
}
func (p *UpdateDIDConfigRequest) SetConfigKv(val map[string]string) {
	p.ConfigKv = val
}

func (p *UpdateDIDConfigRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateDIDConfigRequest) IsSetConfigVersion() bool {
	return p.ConfigVersion != nil
}

func (p *UpdateDIDConfigRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDIDConfigRequest(%+v)", *p)
}

var fieldIDToName_UpdateDIDConfigRequest = map[int16]string{
	1: "base",
	2: "did",
	3: "config_version",
	4: "config_kv",
}

type UpdateDIDConfigResponse struct {
	Base              *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	NewConfigVersion_ *int64           `thrift:"new_config_version,2,optional" frugal:"2,optional,i64" json:"new_config_version,omitempty"`
}

func NewUpdateDIDConfigResponse() *UpdateDIDConfigResponse {
	return &UpdateDIDConfigResponse{}
}

func (p *UpdateDIDConfigResponse) InitDefault() {
}

var UpdateDIDConfigResponse_Base_DEFAULT *common.BaseResp

func (p *UpdateDIDConfigResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return UpdateDIDConfigResponse_Base_DEFAULT
	}
	return p.Base
}

var UpdateDIDConfigResponse_NewConfigVersion__DEFAULT int64

func (p *UpdateDIDConfigResponse) GetNewConfigVersion_() (v int64) {
	if !p.IsSetNewConfigVersion_() {
		return UpdateDIDConfigResponse_NewConfigVersion__DEFAULT
	}
	return *p.NewConfigVersion_
}
func (p *UpdateDIDConfigResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *UpdateDIDConfigResponse) SetNewConfigVersion_(val *int64) {
	p.NewConfigVersion_ = val
}

func (p *UpdateDIDConfigResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateDIDConfigResponse) IsSetNewConfigVersion_() bool {
	return p.NewConfigVersion_ != nil
}

func (p *UpdateDIDConfigResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDIDConfigResponse(%+v)", *p)
}

var fieldIDToName_UpdateDIDConfigResponse = map[int16]string{
	1: "base",
	2: "new_config_version",
}

type DIDService interface {
	CreateDID(ctx context.Context, req *CreateDIDRequest) (r *CreateDIDResponse, err error)

	RegisterDID(ctx context.Context, req *RegisterDIDRequest) (r *RegisterDIDResponse, err error)

	GetDID(ctx context.Context, req *GetDIDRequest) (r *GetDIDResponse, err error)

	VerifySignature(ctx context.Context, req *VerifySignatureRequest) (r *VerifySignatureResponse, err error)

	UpdateDIDConfig(ctx context.Context, req *UpdateDIDConfigRequest) (r *UpdateDIDConfigResponse, err error)
}

type DIDServiceCreateDIDArgs struct {
	Req *CreateDIDRequest `thrift:"req,1" frugal:"1,default,CreateDIDRequest" json:"req"`
}

func NewDIDServiceCreateDIDArgs() *DIDServiceCreateDIDArgs {
	return &DIDServiceCreateDIDArgs{}
}

func (p *DIDServiceCreateDIDArgs) InitDefault() {
}

var DIDServiceCreateDIDArgs_Req_DEFAULT *CreateDIDRequest

func (p *DIDServiceCreateDIDArgs) GetReq() (v *CreateDIDRequest) {
	if !p.IsSetReq() {
		return DIDServiceCreateDIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DIDServiceCreateDIDArgs) SetReq(val *CreateDIDRequest) {
	p.Req = val
}

func (p *DIDServiceCreateDIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DIDServiceCreateDIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceCreateDIDArgs(%+v)", *p)
}

var fieldIDToName_DIDServiceCreateDIDArgs = map[int16]string{
	1: "req",
}

type DIDServiceCreateDIDResult struct {
	Success *CreateDIDResponse `thrift:"success,0,optional" frugal:"0,optional,CreateDIDResponse" json:"success,omitempty"`
}

func NewDIDServiceCreateDIDResult() *DIDServiceCreateDIDResult {
	return &DIDServiceCreateDIDResult{}
}

func (p *DIDServiceCreateDIDResult) InitDefault() {
}

var DIDServiceCreateDIDResult_Success_DEFAULT *CreateDIDResponse

func (p *DIDServiceCreateDIDResult) GetSuccess() (v *CreateDIDResponse) {
	if !p.IsSetSuccess() {
		return DIDServiceCreateDIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DIDServiceCreateDIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateDIDResponse)
}

func (p *DIDServiceCreateDIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DIDServiceCreateDIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceCreateDIDResult(%+v)", *p)
}

var fieldIDToName_DIDServiceCreateDIDResult = map[int16]string{
	0: "success",
}

type DIDServiceRegisterDIDArgs struct {
	Req *RegisterDIDRequest `thrift:"req,1" frugal:"1,default,RegisterDIDRequest" json:"req"`
}

func NewDIDServiceRegisterDIDArgs() *DIDServiceRegisterDIDArgs {
	return &DIDServiceRegisterDIDArgs{}
}

func (p *DIDServiceRegisterDIDArgs) InitDefault() {
}

var DIDServiceRegisterDIDArgs_Req_DEFAULT *RegisterDIDRequest

func (p *DIDServiceRegisterDIDArgs) GetReq() (v *RegisterDIDRequest) {
	if !p.IsSetReq() {
		return DIDServiceRegisterDIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DIDServiceRegisterDIDArgs) SetReq(val *RegisterDIDRequest) {
	p.Req = val
}

func (p *DIDServiceRegisterDIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DIDServiceRegisterDIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceRegisterDIDArgs(%+v)", *p)
}

var fieldIDToName_DIDServiceRegisterDIDArgs = map[int16]string{
	1: "req",
}

type DIDServiceRegisterDIDResult struct {
	Success *RegisterDIDResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterDIDResponse" json:"success,omitempty"`
}

func NewDIDServiceRegisterDIDResult() *DIDServiceRegisterDIDResult {
	return &DIDServiceRegisterDIDResult{}
}

func (p *DIDServiceRegisterDIDResult) InitDefault() {
}

var DIDServiceRegisterDIDResult_Success_DEFAULT *RegisterDIDResponse

func (p *DIDServiceRegisterDIDResult) GetSuccess() (v *RegisterDIDResponse) {
	if !p.IsSetSuccess() {
		return DIDServiceRegisterDIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DIDServiceRegisterDIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterDIDResponse)
}

func (p *DIDServiceRegisterDIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DIDServiceRegisterDIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceRegisterDIDResult(%+v)", *p)
}

var fieldIDToName_DIDServiceRegisterDIDResult = map[int16]string{
	0: "success",
}

type DIDServiceGetDIDArgs struct {
	Req *GetDIDRequest `thrift:"req,1" frugal:"1,default,GetDIDRequest" json:"req"`
}

func NewDIDServiceGetDIDArgs() *DIDServiceGetDIDArgs {
	return &DIDServiceGetDIDArgs{}
}

func (p *DIDServiceGetDIDArgs) InitDefault() {
}

var DIDServiceGetDIDArgs_Req_DEFAULT *GetDIDRequest

func (p *DIDServiceGetDIDArgs) GetReq() (v *GetDIDRequest) {
	if !p.IsSetReq() {
		return DIDServiceGetDIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DIDServiceGetDIDArgs) SetReq(val *GetDIDRequest) {
	p.Req = val
}

func (p *DIDServiceGetDIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DIDServiceGetDIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceGetDIDArgs(%+v)", *p)
}

var fieldIDToName_DIDServiceGetDIDArgs = map[int16]string{
	1: "req",
}

type DIDServiceGetDIDResult struct {
	Success *GetDIDResponse `thrift:"success,0,optional" frugal:"0,optional,GetDIDResponse" json:"success,omitempty"`
}

func NewDIDServiceGetDIDResult() *DIDServiceGetDIDResult {
	return &DIDServiceGetDIDResult{}
}

func (p *DIDServiceGetDIDResult) InitDefault() {
}

var DIDServiceGetDIDResult_Success_DEFAULT *GetDIDResponse

func (p *DIDServiceGetDIDResult) GetSuccess() (v *GetDIDResponse) {
	if !p.IsSetSuccess() {
		return DIDServiceGetDIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DIDServiceGetDIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDIDResponse)
}

func (p *DIDServiceGetDIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DIDServiceGetDIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceGetDIDResult(%+v)", *p)
}

var fieldIDToName_DIDServiceGetDIDResult = map[int16]string{
	0: "success",
}

type DIDServiceVerifySignatureArgs struct {
	Req *VerifySignatureRequest `thrift:"req,1" frugal:"1,default,VerifySignatureRequest" json:"req"`
}

func NewDIDServiceVerifySignatureArgs() *DIDServiceVerifySignatureArgs {
	return &DIDServiceVerifySignatureArgs{}
}

func (p *DIDServiceVerifySignatureArgs) InitDefault() {
}

var DIDServiceVerifySignatureArgs_Req_DEFAULT *VerifySignatureRequest

func (p *DIDServiceVerifySignatureArgs) GetReq() (v *VerifySignatureRequest) {
	if !p.IsSetReq() {
		return DIDServiceVerifySignatureArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DIDServiceVerifySignatureArgs) SetReq(val *VerifySignatureRequest) {
	p.Req = val
}

func (p *DIDServiceVerifySignatureArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DIDServiceVerifySignatureArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceVerifySignatureArgs(%+v)", *p)
}

var fieldIDToName_DIDServiceVerifySignatureArgs = map[int16]string{
	1: "req",
}

type DIDServiceVerifySignatureResult struct {
	Success *VerifySignatureResponse `thrift:"success,0,optional" frugal:"0,optional,VerifySignatureResponse" json:"success,omitempty"`
}

func NewDIDServiceVerifySignatureResult() *DIDServiceVerifySignatureResult {
	return &DIDServiceVerifySignatureResult{}
}

func (p *DIDServiceVerifySignatureResult) InitDefault() {
}

var DIDServiceVerifySignatureResult_Success_DEFAULT *VerifySignatureResponse

func (p *DIDServiceVerifySignatureResult) GetSuccess() (v *VerifySignatureResponse) {
	if !p.IsSetSuccess() {
		return DIDServiceVerifySignatureResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DIDServiceVerifySignatureResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifySignatureResponse)
}

func (p *DIDServiceVerifySignatureResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DIDServiceVerifySignatureResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceVerifySignatureResult(%+v)", *p)
}

var fieldIDToName_DIDServiceVerifySignatureResult = map[int16]string{
	0: "success",
}

type DIDServiceUpdateDIDConfigArgs struct {
	Req *UpdateDIDConfigRequest `thrift:"req,1" frugal:"1,default,UpdateDIDConfigRequest" json:"req"`
}

func NewDIDServiceUpdateDIDConfigArgs() *DIDServiceUpdateDIDConfigArgs {
	return &DIDServiceUpdateDIDConfigArgs{}
}

func (p *DIDServiceUpdateDIDConfigArgs) InitDefault() {
}

var DIDServiceUpdateDIDConfigArgs_Req_DEFAULT *UpdateDIDConfigRequest

func (p *DIDServiceUpdateDIDConfigArgs) GetReq() (v *UpdateDIDConfigRequest) {
	if !p.IsSetReq() {
		return DIDServiceUpdateDIDConfigArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DIDServiceUpdateDIDConfigArgs) SetReq(val *UpdateDIDConfigRequest) {
	p.Req = val
}

func (p *DIDServiceUpdateDIDConfigArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DIDServiceUpdateDIDConfigArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceUpdateDIDConfigArgs(%+v)", *p)
}

var fieldIDToName_DIDServiceUpdateDIDConfigArgs = map[int16]string{
	1: "req",
}

type DIDServiceUpdateDIDConfigResult struct {
	Success *UpdateDIDConfigResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateDIDConfigResponse" json:"success,omitempty"`
}

func NewDIDServiceUpdateDIDConfigResult() *DIDServiceUpdateDIDConfigResult {
	return &DIDServiceUpdateDIDConfigResult{}
}

func (p *DIDServiceUpdateDIDConfigResult) InitDefault() {
}

var DIDServiceUpdateDIDConfigResult_Success_DEFAULT *UpdateDIDConfigResponse

func (p *DIDServiceUpdateDIDConfigResult) GetSuccess() (v *UpdateDIDConfigResponse) {
	if !p.IsSetSuccess() {
		return DIDServiceUpdateDIDConfigResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DIDServiceUpdateDIDConfigResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateDIDConfigResponse)
}

func (p *DIDServiceUpdateDIDConfigResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DIDServiceUpdateDIDConfigResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DIDServiceUpdateDIDConfigResult(%+v)", *p)
}

var fieldIDToName_DIDServiceUpdateDIDConfigResult = map[int16]string{
	0: "success",
}
