apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-blockchain-adapter
  namespace: stablepay-dev
spec:
  template:
    spec:
      containers:
        - name: blockchain-adapter
          command:
            - /app/server
          args:
            - -config
            - conf/docker.yaml
