// Code generated by Kitex v0.16.1. DO NOT EDIT.

package queryservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	query_service "query-service/kitex_gen/stablepay/query_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetBalanceSummary": kitex.NewMethodInfo(
		getBalanceSummaryHandler,
		newQueryServiceGetBalanceSummaryArgs,
		newQueryServiceGetBalanceSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTransactions": kitex.NewMethodInfo(
		listTransactionsHandler,
		newQueryServiceListTransactionsArgs,
		newQueryServiceListTransactionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRevenueSummary": kitex.NewMethodInfo(
		getRevenueSummaryHandler,
		newQueryServiceGetRevenueSummaryArgs,
		newQueryServiceGetRevenueSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSales": kitex.NewMethodInfo(
		listSalesHandler,
		newQueryServiceListSalesArgs,
		newQueryServiceListSalesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	queryServiceServiceInfo                = NewServiceInfo()
	queryServiceServiceInfoForClient       = NewServiceInfoForClient()
	queryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return queryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return queryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return queryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "QueryService"
	handlerType := (*query_service.QueryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "query_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getBalanceSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*query_service.QueryServiceGetBalanceSummaryArgs)
	realResult := result.(*query_service.QueryServiceGetBalanceSummaryResult)
	success, err := handler.(query_service.QueryService).GetBalanceSummary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQueryServiceGetBalanceSummaryArgs() interface{} {
	return query_service.NewQueryServiceGetBalanceSummaryArgs()
}

func newQueryServiceGetBalanceSummaryResult() interface{} {
	return query_service.NewQueryServiceGetBalanceSummaryResult()
}

func listTransactionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*query_service.QueryServiceListTransactionsArgs)
	realResult := result.(*query_service.QueryServiceListTransactionsResult)
	success, err := handler.(query_service.QueryService).ListTransactions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQueryServiceListTransactionsArgs() interface{} {
	return query_service.NewQueryServiceListTransactionsArgs()
}

func newQueryServiceListTransactionsResult() interface{} {
	return query_service.NewQueryServiceListTransactionsResult()
}

func getRevenueSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*query_service.QueryServiceGetRevenueSummaryArgs)
	realResult := result.(*query_service.QueryServiceGetRevenueSummaryResult)
	success, err := handler.(query_service.QueryService).GetRevenueSummary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQueryServiceGetRevenueSummaryArgs() interface{} {
	return query_service.NewQueryServiceGetRevenueSummaryArgs()
}

func newQueryServiceGetRevenueSummaryResult() interface{} {
	return query_service.NewQueryServiceGetRevenueSummaryResult()
}

func listSalesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*query_service.QueryServiceListSalesArgs)
	realResult := result.(*query_service.QueryServiceListSalesResult)
	success, err := handler.(query_service.QueryService).ListSales(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQueryServiceListSalesArgs() interface{} {
	return query_service.NewQueryServiceListSalesArgs()
}

func newQueryServiceListSalesResult() interface{} {
	return query_service.NewQueryServiceListSalesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetBalanceSummary(ctx context.Context, req *query_service.GetBalanceSummaryRequest) (r *query_service.GetBalanceSummaryResponse, err error) {
	var _args query_service.QueryServiceGetBalanceSummaryArgs
	_args.Req = req
	var _result query_service.QueryServiceGetBalanceSummaryResult
	if err = p.c.Call(ctx, "GetBalanceSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTransactions(ctx context.Context, req *query_service.ListTransactionsRequest) (r *query_service.ListTransactionsResponse, err error) {
	var _args query_service.QueryServiceListTransactionsArgs
	_args.Req = req
	var _result query_service.QueryServiceListTransactionsResult
	if err = p.c.Call(ctx, "ListTransactions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRevenueSummary(ctx context.Context, req *query_service.GetRevenueSummaryRequest) (r *query_service.GetRevenueSummaryResponse, err error) {
	var _args query_service.QueryServiceGetRevenueSummaryArgs
	_args.Req = req
	var _result query_service.QueryServiceGetRevenueSummaryResult
	if err = p.c.Call(ctx, "GetRevenueSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSales(ctx context.Context, req *query_service.ListSalesRequest) (r *query_service.ListSalesResponse, err error) {
	var _args query_service.QueryServiceListSalesArgs
	_args.Req = req
	var _result query_service.QueryServiceListSalesResult
	if err = p.c.Call(ctx, "ListSales", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
