// Code generated by Kitex v0.16.1. DO NOT EDIT.
package queryservice

import (
	server "github.com/cloudwego/kitex/server"
	query_service "github.com/stablepay/query-service/kitex_gen/stablepay/query_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler query_service.QueryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler query_service.QueryService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
