// Code generated by Kitex v0.16.1. DO NOT EDIT.

package queryservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	query_service "stablepay/api-gateway/kitex_gen/stablepay/query_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetBalanceSummary(ctx context.Context, req *query_service.GetBalanceSummaryRequest, callOptions ...callopt.Option) (r *query_service.GetBalanceSummaryResponse, err error)
	ListTransactions(ctx context.Context, req *query_service.ListTransactionsRequest, callOptions ...callopt.Option) (r *query_service.ListTransactionsResponse, err error)
	GetRevenueSummary(ctx context.Context, req *query_service.GetRevenueSummaryRequest, callOptions ...callopt.Option) (r *query_service.GetRevenueSummaryResponse, err error)
	ListSales(ctx context.Context, req *query_service.ListSalesRequest, callOptions ...callopt.Option) (r *query_service.ListSalesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kQueryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kQueryServiceClient struct {
	*kClient
}

func (p *kQueryServiceClient) GetBalanceSummary(ctx context.Context, req *query_service.GetBalanceSummaryRequest, callOptions ...callopt.Option) (r *query_service.GetBalanceSummaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBalanceSummary(ctx, req)
}

func (p *kQueryServiceClient) ListTransactions(ctx context.Context, req *query_service.ListTransactionsRequest, callOptions ...callopt.Option) (r *query_service.ListTransactionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTransactions(ctx, req)
}

func (p *kQueryServiceClient) GetRevenueSummary(ctx context.Context, req *query_service.GetRevenueSummaryRequest, callOptions ...callopt.Option) (r *query_service.GetRevenueSummaryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRevenueSummary(ctx, req)
}

func (p *kQueryServiceClient) ListSales(ctx context.Context, req *query_service.ListSalesRequest, callOptions ...callopt.Option) (r *query_service.ListSalesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSales(ctx, req)
}
