// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package verification_service

import (
	"context"
	"fmt"
	"verification-service/kitex_gen/stablepay/common"
)

type VerifyPurchaseRequest struct {
	Base     *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDid common.DID      `thrift:"skill_did,3" frugal:"3,default,string" json:"skill_did"`
}

func NewVerifyPurchaseRequest() *VerifyPurchaseRequest {
	return &VerifyPurchaseRequest{}
}

func (p *VerifyPurchaseRequest) InitDefault() {
}

var VerifyPurchaseRequest_Base_DEFAULT *common.BaseReq

func (p *VerifyPurchaseRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return VerifyPurchaseRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyPurchaseRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *VerifyPurchaseRequest) GetSkillDid() (v common.DID) {
	return p.SkillDid
}
func (p *VerifyPurchaseRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *VerifyPurchaseRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *VerifyPurchaseRequest) SetSkillDid(val common.DID) {
	p.SkillDid = val
}

func (p *VerifyPurchaseRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyPurchaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyPurchaseRequest(%+v)", *p)
}

var fieldIDToName_VerifyPurchaseRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_did",
}

type VerifyPurchaseResponse struct {
	Base         *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Purchased    bool             `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string          `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId     `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
	AmountMinor  *int64           `thrift:"amount_minor,5,optional" frugal:"5,optional,i64" json:"amount_minor,omitempty"`
	Currency     *common.Currency `thrift:"currency,6,optional" frugal:"6,optional,Currency" json:"currency,omitempty"`
}

func NewVerifyPurchaseResponse() *VerifyPurchaseResponse {
	return &VerifyPurchaseResponse{}
}

func (p *VerifyPurchaseResponse) InitDefault() {
}

var VerifyPurchaseResponse_Base_DEFAULT *common.BaseResp

func (p *VerifyPurchaseResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return VerifyPurchaseResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyPurchaseResponse) GetPurchased() (v bool) {
	return p.Purchased
}

var VerifyPurchaseResponse_PurchaseTime_DEFAULT string

func (p *VerifyPurchaseResponse) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return VerifyPurchaseResponse_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var VerifyPurchaseResponse_TxId_DEFAULT common.TxId

func (p *VerifyPurchaseResponse) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return VerifyPurchaseResponse_TxId_DEFAULT
	}
	return *p.TxId
}

var VerifyPurchaseResponse_AmountMinor_DEFAULT int64

func (p *VerifyPurchaseResponse) GetAmountMinor() (v int64) {
	if !p.IsSetAmountMinor() {
		return VerifyPurchaseResponse_AmountMinor_DEFAULT
	}
	return *p.AmountMinor
}

var VerifyPurchaseResponse_Currency_DEFAULT common.Currency

func (p *VerifyPurchaseResponse) GetCurrency() (v common.Currency) {
	if !p.IsSetCurrency() {
		return VerifyPurchaseResponse_Currency_DEFAULT
	}
	return *p.Currency
}
func (p *VerifyPurchaseResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *VerifyPurchaseResponse) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *VerifyPurchaseResponse) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *VerifyPurchaseResponse) SetTxId(val *common.TxId) {
	p.TxId = val
}
func (p *VerifyPurchaseResponse) SetAmountMinor(val *int64) {
	p.AmountMinor = val
}
func (p *VerifyPurchaseResponse) SetCurrency(val *common.Currency) {
	p.Currency = val
}

func (p *VerifyPurchaseResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyPurchaseResponse) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *VerifyPurchaseResponse) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *VerifyPurchaseResponse) IsSetAmountMinor() bool {
	return p.AmountMinor != nil
}

func (p *VerifyPurchaseResponse) IsSetCurrency() bool {
	return p.Currency != nil
}

func (p *VerifyPurchaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyPurchaseResponse(%+v)", *p)
}

var fieldIDToName_VerifyPurchaseResponse = map[int16]string{
	1: "base",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
	5: "amount_minor",
	6: "currency",
}

type BatchVerifyItem struct {
	SkillDid     common.DID   `thrift:"skill_did,1" frugal:"1,default,string" json:"skill_did"`
	Purchased    bool         `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string      `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
}

func NewBatchVerifyItem() *BatchVerifyItem {
	return &BatchVerifyItem{}
}

func (p *BatchVerifyItem) InitDefault() {
}

func (p *BatchVerifyItem) GetSkillDid() (v common.DID) {
	return p.SkillDid
}

func (p *BatchVerifyItem) GetPurchased() (v bool) {
	return p.Purchased
}

var BatchVerifyItem_PurchaseTime_DEFAULT string

func (p *BatchVerifyItem) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return BatchVerifyItem_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var BatchVerifyItem_TxId_DEFAULT common.TxId

func (p *BatchVerifyItem) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return BatchVerifyItem_TxId_DEFAULT
	}
	return *p.TxId
}
func (p *BatchVerifyItem) SetSkillDid(val common.DID) {
	p.SkillDid = val
}
func (p *BatchVerifyItem) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *BatchVerifyItem) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *BatchVerifyItem) SetTxId(val *common.TxId) {
	p.TxId = val
}

func (p *BatchVerifyItem) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *BatchVerifyItem) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *BatchVerifyItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyItem(%+v)", *p)
}

var fieldIDToName_BatchVerifyItem = map[int16]string{
	1: "skill_did",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
}

type BatchVerifyPurchaseRequest struct {
	Base      *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid  common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDids []common.DID    `thrift:"skill_dids,3" frugal:"3,default,list<string>" json:"skill_dids"`
}

func NewBatchVerifyPurchaseRequest() *BatchVerifyPurchaseRequest {
	return &BatchVerifyPurchaseRequest{}
}

func (p *BatchVerifyPurchaseRequest) InitDefault() {
}

var BatchVerifyPurchaseRequest_Base_DEFAULT *common.BaseReq

func (p *BatchVerifyPurchaseRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return BatchVerifyPurchaseRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *BatchVerifyPurchaseRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *BatchVerifyPurchaseRequest) GetSkillDids() (v []common.DID) {
	return p.SkillDids
}
func (p *BatchVerifyPurchaseRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *BatchVerifyPurchaseRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *BatchVerifyPurchaseRequest) SetSkillDids(val []common.DID) {
	p.SkillDids = val
}

func (p *BatchVerifyPurchaseRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchVerifyPurchaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyPurchaseRequest(%+v)", *p)
}

var fieldIDToName_BatchVerifyPurchaseRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_dids",
}

type BatchVerifyPurchaseResponse struct {
	Base  *common.BaseResp   `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Items []*BatchVerifyItem `thrift:"items,2" frugal:"2,default,list<BatchVerifyItem>" json:"items"`
}

func NewBatchVerifyPurchaseResponse() *BatchVerifyPurchaseResponse {
	return &BatchVerifyPurchaseResponse{}
}

func (p *BatchVerifyPurchaseResponse) InitDefault() {
}

var BatchVerifyPurchaseResponse_Base_DEFAULT *common.BaseResp

func (p *BatchVerifyPurchaseResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return BatchVerifyPurchaseResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *BatchVerifyPurchaseResponse) GetItems() (v []*BatchVerifyItem) {
	return p.Items
}
func (p *BatchVerifyPurchaseResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *BatchVerifyPurchaseResponse) SetItems(val []*BatchVerifyItem) {
	p.Items = val
}

func (p *BatchVerifyPurchaseResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchVerifyPurchaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVerifyPurchaseResponse(%+v)", *p)
}

var fieldIDToName_BatchVerifyPurchaseResponse = map[int16]string{
	1: "base",
	2: "items",
}

type GetPurchaseProofRequest struct {
	Base     *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDid common.DID      `thrift:"skill_did,3" frugal:"3,default,string" json:"skill_did"`
}

func NewGetPurchaseProofRequest() *GetPurchaseProofRequest {
	return &GetPurchaseProofRequest{}
}

func (p *GetPurchaseProofRequest) InitDefault() {
}

var GetPurchaseProofRequest_Base_DEFAULT *common.BaseReq

func (p *GetPurchaseProofRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetPurchaseProofRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPurchaseProofRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *GetPurchaseProofRequest) GetSkillDid() (v common.DID) {
	return p.SkillDid
}
func (p *GetPurchaseProofRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetPurchaseProofRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *GetPurchaseProofRequest) SetSkillDid(val common.DID) {
	p.SkillDid = val
}

func (p *GetPurchaseProofRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPurchaseProofRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPurchaseProofRequest(%+v)", *p)
}

var fieldIDToName_GetPurchaseProofRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_did",
}

type GetPurchaseProofResponse struct {
	Base         *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Purchased    bool             `thrift:"purchased,2" frugal:"2,default,bool" json:"purchased"`
	PurchaseTime *string          `thrift:"purchase_time,3,optional" frugal:"3,optional,string" json:"purchase_time,omitempty"`
	TxId         *common.TxId     `thrift:"tx_id,4,optional" frugal:"4,optional,string" json:"tx_id,omitempty"`
	AmountMinor  *int64           `thrift:"amount_minor,5,optional" frugal:"5,optional,i64" json:"amount_minor,omitempty"`
	Currency     *common.Currency `thrift:"currency,6,optional" frugal:"6,optional,Currency" json:"currency,omitempty"`
	TxHash       *common.TxHash   `thrift:"tx_hash,7,optional" frugal:"7,optional,string" json:"tx_hash,omitempty"`
	ProofVersion *string          `thrift:"proof_version,8,optional" frugal:"8,optional,string" json:"proof_version,omitempty"`
}

func NewGetPurchaseProofResponse() *GetPurchaseProofResponse {
	return &GetPurchaseProofResponse{}
}

func (p *GetPurchaseProofResponse) InitDefault() {
}

var GetPurchaseProofResponse_Base_DEFAULT *common.BaseResp

func (p *GetPurchaseProofResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetPurchaseProofResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPurchaseProofResponse) GetPurchased() (v bool) {
	return p.Purchased
}

var GetPurchaseProofResponse_PurchaseTime_DEFAULT string

func (p *GetPurchaseProofResponse) GetPurchaseTime() (v string) {
	if !p.IsSetPurchaseTime() {
		return GetPurchaseProofResponse_PurchaseTime_DEFAULT
	}
	return *p.PurchaseTime
}

var GetPurchaseProofResponse_TxId_DEFAULT common.TxId

func (p *GetPurchaseProofResponse) GetTxId() (v common.TxId) {
	if !p.IsSetTxId() {
		return GetPurchaseProofResponse_TxId_DEFAULT
	}
	return *p.TxId
}

var GetPurchaseProofResponse_AmountMinor_DEFAULT int64

func (p *GetPurchaseProofResponse) GetAmountMinor() (v int64) {
	if !p.IsSetAmountMinor() {
		return GetPurchaseProofResponse_AmountMinor_DEFAULT
	}
	return *p.AmountMinor
}

var GetPurchaseProofResponse_Currency_DEFAULT common.Currency

func (p *GetPurchaseProofResponse) GetCurrency() (v common.Currency) {
	if !p.IsSetCurrency() {
		return GetPurchaseProofResponse_Currency_DEFAULT
	}
	return *p.Currency
}

var GetPurchaseProofResponse_TxHash_DEFAULT common.TxHash

func (p *GetPurchaseProofResponse) GetTxHash() (v common.TxHash) {
	if !p.IsSetTxHash() {
		return GetPurchaseProofResponse_TxHash_DEFAULT
	}
	return *p.TxHash
}

var GetPurchaseProofResponse_ProofVersion_DEFAULT string

func (p *GetPurchaseProofResponse) GetProofVersion() (v string) {
	if !p.IsSetProofVersion() {
		return GetPurchaseProofResponse_ProofVersion_DEFAULT
	}
	return *p.ProofVersion
}
func (p *GetPurchaseProofResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetPurchaseProofResponse) SetPurchased(val bool) {
	p.Purchased = val
}
func (p *GetPurchaseProofResponse) SetPurchaseTime(val *string) {
	p.PurchaseTime = val
}
func (p *GetPurchaseProofResponse) SetTxId(val *common.TxId) {
	p.TxId = val
}
func (p *GetPurchaseProofResponse) SetAmountMinor(val *int64) {
	p.AmountMinor = val
}
func (p *GetPurchaseProofResponse) SetCurrency(val *common.Currency) {
	p.Currency = val
}
func (p *GetPurchaseProofResponse) SetTxHash(val *common.TxHash) {
	p.TxHash = val
}
func (p *GetPurchaseProofResponse) SetProofVersion(val *string) {
	p.ProofVersion = val
}

func (p *GetPurchaseProofResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPurchaseProofResponse) IsSetPurchaseTime() bool {
	return p.PurchaseTime != nil
}

func (p *GetPurchaseProofResponse) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *GetPurchaseProofResponse) IsSetAmountMinor() bool {
	return p.AmountMinor != nil
}

func (p *GetPurchaseProofResponse) IsSetCurrency() bool {
	return p.Currency != nil
}

func (p *GetPurchaseProofResponse) IsSetTxHash() bool {
	return p.TxHash != nil
}

func (p *GetPurchaseProofResponse) IsSetProofVersion() bool {
	return p.ProofVersion != nil
}

func (p *GetPurchaseProofResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPurchaseProofResponse(%+v)", *p)
}

var fieldIDToName_GetPurchaseProofResponse = map[int16]string{
	1: "base",
	2: "purchased",
	3: "purchase_time",
	4: "tx_id",
	5: "amount_minor",
	6: "currency",
	7: "tx_hash",
	8: "proof_version",
}

type VerifyXTweetRequest struct {
	Base          *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid      common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	WalletAddress string          `thrift:"wallet_address,3" frugal:"3,default,string" json:"wallet_address"`
	TweetUrl      string          `thrift:"tweet_url,4" frugal:"4,default,string" json:"tweet_url"`
}

func NewVerifyXTweetRequest() *VerifyXTweetRequest {
	return &VerifyXTweetRequest{}
}

func (p *VerifyXTweetRequest) InitDefault() {
}

var VerifyXTweetRequest_Base_DEFAULT *common.BaseReq

func (p *VerifyXTweetRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return VerifyXTweetRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyXTweetRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *VerifyXTweetRequest) GetWalletAddress() (v string) {
	return p.WalletAddress
}

func (p *VerifyXTweetRequest) GetTweetUrl() (v string) {
	return p.TweetUrl
}
func (p *VerifyXTweetRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *VerifyXTweetRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *VerifyXTweetRequest) SetWalletAddress(val string) {
	p.WalletAddress = val
}
func (p *VerifyXTweetRequest) SetTweetUrl(val string) {
	p.TweetUrl = val
}

func (p *VerifyXTweetRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyXTweetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyXTweetRequest(%+v)", *p)
}

var fieldIDToName_VerifyXTweetRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "wallet_address",
	4: "tweet_url",
}

type VerifyXTweetResponse struct {
	Base              *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Verified          bool             `thrift:"verified,2" frugal:"2,default,bool" json:"verified"`
	Message           *string          `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	RewardAmountMinor *int64           `thrift:"reward_amount_minor,4,optional" frugal:"4,optional,i64" json:"reward_amount_minor,omitempty"`
	RewardTxId        *string          `thrift:"reward_tx_id,5,optional" frugal:"5,optional,string" json:"reward_tx_id,omitempty"`
}

func NewVerifyXTweetResponse() *VerifyXTweetResponse {
	return &VerifyXTweetResponse{}
}

func (p *VerifyXTweetResponse) InitDefault() {
}

var VerifyXTweetResponse_Base_DEFAULT *common.BaseResp

func (p *VerifyXTweetResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return VerifyXTweetResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyXTweetResponse) GetVerified() (v bool) {
	return p.Verified
}

var VerifyXTweetResponse_Message_DEFAULT string

func (p *VerifyXTweetResponse) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return VerifyXTweetResponse_Message_DEFAULT
	}
	return *p.Message
}

var VerifyXTweetResponse_RewardAmountMinor_DEFAULT int64

func (p *VerifyXTweetResponse) GetRewardAmountMinor() (v int64) {
	if !p.IsSetRewardAmountMinor() {
		return VerifyXTweetResponse_RewardAmountMinor_DEFAULT
	}
	return *p.RewardAmountMinor
}

var VerifyXTweetResponse_RewardTxId_DEFAULT string

func (p *VerifyXTweetResponse) GetRewardTxId() (v string) {
	if !p.IsSetRewardTxId() {
		return VerifyXTweetResponse_RewardTxId_DEFAULT
	}
	return *p.RewardTxId
}
func (p *VerifyXTweetResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *VerifyXTweetResponse) SetVerified(val bool) {
	p.Verified = val
}
func (p *VerifyXTweetResponse) SetMessage(val *string) {
	p.Message = val
}
func (p *VerifyXTweetResponse) SetRewardAmountMinor(val *int64) {
	p.RewardAmountMinor = val
}
func (p *VerifyXTweetResponse) SetRewardTxId(val *string) {
	p.RewardTxId = val
}

func (p *VerifyXTweetResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyXTweetResponse) IsSetMessage() bool {
	return p.Message != nil
}

func (p *VerifyXTweetResponse) IsSetRewardAmountMinor() bool {
	return p.RewardAmountMinor != nil
}

func (p *VerifyXTweetResponse) IsSetRewardTxId() bool {
	return p.RewardTxId != nil
}

func (p *VerifyXTweetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyXTweetResponse(%+v)", *p)
}

var fieldIDToName_VerifyXTweetResponse = map[int16]string{
	1: "base",
	2: "verified",
	3: "message",
	4: "reward_amount_minor",
	5: "reward_tx_id",
}

type GetXVerificationStatusRequest struct {
	Base     *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
}

func NewGetXVerificationStatusRequest() *GetXVerificationStatusRequest {
	return &GetXVerificationStatusRequest{}
}

func (p *GetXVerificationStatusRequest) InitDefault() {
}

var GetXVerificationStatusRequest_Base_DEFAULT *common.BaseReq

func (p *GetXVerificationStatusRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetXVerificationStatusRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetXVerificationStatusRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}
func (p *GetXVerificationStatusRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetXVerificationStatusRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}

func (p *GetXVerificationStatusRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetXVerificationStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetXVerificationStatusRequest(%+v)", *p)
}

var fieldIDToName_GetXVerificationStatusRequest = map[int16]string{
	1: "base",
	2: "agent_did",
}

type GetXVerificationStatusResponse struct {
	Base              *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Verified          bool             `thrift:"verified,2" frugal:"2,default,bool" json:"verified"`
	TweetUrl          *string          `thrift:"tweet_url,3,optional" frugal:"3,optional,string" json:"tweet_url,omitempty"`
	VerifiedAt        *string          `thrift:"verified_at,4,optional" frugal:"4,optional,string" json:"verified_at,omitempty"`
	RewardAmountMinor *int64           `thrift:"reward_amount_minor,5,optional" frugal:"5,optional,i64" json:"reward_amount_minor,omitempty"`
	RewardTxId        *string          `thrift:"reward_tx_id,6,optional" frugal:"6,optional,string" json:"reward_tx_id,omitempty"`
}

func NewGetXVerificationStatusResponse() *GetXVerificationStatusResponse {
	return &GetXVerificationStatusResponse{}
}

func (p *GetXVerificationStatusResponse) InitDefault() {
}

var GetXVerificationStatusResponse_Base_DEFAULT *common.BaseResp

func (p *GetXVerificationStatusResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetXVerificationStatusResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetXVerificationStatusResponse) GetVerified() (v bool) {
	return p.Verified
}

var GetXVerificationStatusResponse_TweetUrl_DEFAULT string

func (p *GetXVerificationStatusResponse) GetTweetUrl() (v string) {
	if !p.IsSetTweetUrl() {
		return GetXVerificationStatusResponse_TweetUrl_DEFAULT
	}
	return *p.TweetUrl
}

var GetXVerificationStatusResponse_VerifiedAt_DEFAULT string

func (p *GetXVerificationStatusResponse) GetVerifiedAt() (v string) {
	if !p.IsSetVerifiedAt() {
		return GetXVerificationStatusResponse_VerifiedAt_DEFAULT
	}
	return *p.VerifiedAt
}

var GetXVerificationStatusResponse_RewardAmountMinor_DEFAULT int64

func (p *GetXVerificationStatusResponse) GetRewardAmountMinor() (v int64) {
	if !p.IsSetRewardAmountMinor() {
		return GetXVerificationStatusResponse_RewardAmountMinor_DEFAULT
	}
	return *p.RewardAmountMinor
}

var GetXVerificationStatusResponse_RewardTxId_DEFAULT string

func (p *GetXVerificationStatusResponse) GetRewardTxId() (v string) {
	if !p.IsSetRewardTxId() {
		return GetXVerificationStatusResponse_RewardTxId_DEFAULT
	}
	return *p.RewardTxId
}
func (p *GetXVerificationStatusResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetXVerificationStatusResponse) SetVerified(val bool) {
	p.Verified = val
}
func (p *GetXVerificationStatusResponse) SetTweetUrl(val *string) {
	p.TweetUrl = val
}
func (p *GetXVerificationStatusResponse) SetVerifiedAt(val *string) {
	p.VerifiedAt = val
}
func (p *GetXVerificationStatusResponse) SetRewardAmountMinor(val *int64) {
	p.RewardAmountMinor = val
}
func (p *GetXVerificationStatusResponse) SetRewardTxId(val *string) {
	p.RewardTxId = val
}

func (p *GetXVerificationStatusResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetXVerificationStatusResponse) IsSetTweetUrl() bool {
	return p.TweetUrl != nil
}

func (p *GetXVerificationStatusResponse) IsSetVerifiedAt() bool {
	return p.VerifiedAt != nil
}

func (p *GetXVerificationStatusResponse) IsSetRewardAmountMinor() bool {
	return p.RewardAmountMinor != nil
}

func (p *GetXVerificationStatusResponse) IsSetRewardTxId() bool {
	return p.RewardTxId != nil
}

func (p *GetXVerificationStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetXVerificationStatusResponse(%+v)", *p)
}

var fieldIDToName_GetXVerificationStatusResponse = map[int16]string{
	1: "base",
	2: "verified",
	3: "tweet_url",
	4: "verified_at",
	5: "reward_amount_minor",
	6: "reward_tx_id",
}

type VerificationService interface {
	VerifyPurchase(ctx context.Context, req *VerifyPurchaseRequest) (r *VerifyPurchaseResponse, err error)

	BatchVerifyPurchase(ctx context.Context, req *BatchVerifyPurchaseRequest) (r *BatchVerifyPurchaseResponse, err error)

	GetPurchaseProof(ctx context.Context, req *GetPurchaseProofRequest) (r *GetPurchaseProofResponse, err error)

	VerifyXTweet(ctx context.Context, req *VerifyXTweetRequest) (r *VerifyXTweetResponse, err error)

	GetXVerificationStatus(ctx context.Context, req *GetXVerificationStatusRequest) (r *GetXVerificationStatusResponse, err error)
}

type VerificationServiceVerifyPurchaseArgs struct {
	Req *VerifyPurchaseRequest `thrift:"req,1" frugal:"1,default,VerifyPurchaseRequest" json:"req"`
}

func NewVerificationServiceVerifyPurchaseArgs() *VerificationServiceVerifyPurchaseArgs {
	return &VerificationServiceVerifyPurchaseArgs{}
}

func (p *VerificationServiceVerifyPurchaseArgs) InitDefault() {
}

var VerificationServiceVerifyPurchaseArgs_Req_DEFAULT *VerifyPurchaseRequest

func (p *VerificationServiceVerifyPurchaseArgs) GetReq() (v *VerifyPurchaseRequest) {
	if !p.IsSetReq() {
		return VerificationServiceVerifyPurchaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceVerifyPurchaseArgs) SetReq(val *VerifyPurchaseRequest) {
	p.Req = val
}

func (p *VerificationServiceVerifyPurchaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceVerifyPurchaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyPurchaseArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyPurchaseArgs = map[int16]string{
	1: "req",
}

type VerificationServiceVerifyPurchaseResult struct {
	Success *VerifyPurchaseResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyPurchaseResponse" json:"success,omitempty"`
}

func NewVerificationServiceVerifyPurchaseResult() *VerificationServiceVerifyPurchaseResult {
	return &VerificationServiceVerifyPurchaseResult{}
}

func (p *VerificationServiceVerifyPurchaseResult) InitDefault() {
}

var VerificationServiceVerifyPurchaseResult_Success_DEFAULT *VerifyPurchaseResponse

func (p *VerificationServiceVerifyPurchaseResult) GetSuccess() (v *VerifyPurchaseResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceVerifyPurchaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceVerifyPurchaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyPurchaseResponse)
}

func (p *VerificationServiceVerifyPurchaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceVerifyPurchaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyPurchaseResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyPurchaseResult = map[int16]string{
	0: "success",
}

type VerificationServiceBatchVerifyPurchaseArgs struct {
	Req *BatchVerifyPurchaseRequest `thrift:"req,1" frugal:"1,default,BatchVerifyPurchaseRequest" json:"req"`
}

func NewVerificationServiceBatchVerifyPurchaseArgs() *VerificationServiceBatchVerifyPurchaseArgs {
	return &VerificationServiceBatchVerifyPurchaseArgs{}
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) InitDefault() {
}

var VerificationServiceBatchVerifyPurchaseArgs_Req_DEFAULT *BatchVerifyPurchaseRequest

func (p *VerificationServiceBatchVerifyPurchaseArgs) GetReq() (v *BatchVerifyPurchaseRequest) {
	if !p.IsSetReq() {
		return VerificationServiceBatchVerifyPurchaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceBatchVerifyPurchaseArgs) SetReq(val *BatchVerifyPurchaseRequest) {
	p.Req = val
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceBatchVerifyPurchaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceBatchVerifyPurchaseArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceBatchVerifyPurchaseArgs = map[int16]string{
	1: "req",
}

type VerificationServiceBatchVerifyPurchaseResult struct {
	Success *BatchVerifyPurchaseResponse `thrift:"success,0,optional" frugal:"0,optional,BatchVerifyPurchaseResponse" json:"success,omitempty"`
}

func NewVerificationServiceBatchVerifyPurchaseResult() *VerificationServiceBatchVerifyPurchaseResult {
	return &VerificationServiceBatchVerifyPurchaseResult{}
}

func (p *VerificationServiceBatchVerifyPurchaseResult) InitDefault() {
}

var VerificationServiceBatchVerifyPurchaseResult_Success_DEFAULT *BatchVerifyPurchaseResponse

func (p *VerificationServiceBatchVerifyPurchaseResult) GetSuccess() (v *BatchVerifyPurchaseResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceBatchVerifyPurchaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceBatchVerifyPurchaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchVerifyPurchaseResponse)
}

func (p *VerificationServiceBatchVerifyPurchaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceBatchVerifyPurchaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceBatchVerifyPurchaseResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceBatchVerifyPurchaseResult = map[int16]string{
	0: "success",
}

type VerificationServiceGetPurchaseProofArgs struct {
	Req *GetPurchaseProofRequest `thrift:"req,1" frugal:"1,default,GetPurchaseProofRequest" json:"req"`
}

func NewVerificationServiceGetPurchaseProofArgs() *VerificationServiceGetPurchaseProofArgs {
	return &VerificationServiceGetPurchaseProofArgs{}
}

func (p *VerificationServiceGetPurchaseProofArgs) InitDefault() {
}

var VerificationServiceGetPurchaseProofArgs_Req_DEFAULT *GetPurchaseProofRequest

func (p *VerificationServiceGetPurchaseProofArgs) GetReq() (v *GetPurchaseProofRequest) {
	if !p.IsSetReq() {
		return VerificationServiceGetPurchaseProofArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceGetPurchaseProofArgs) SetReq(val *GetPurchaseProofRequest) {
	p.Req = val
}

func (p *VerificationServiceGetPurchaseProofArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceGetPurchaseProofArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetPurchaseProofArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetPurchaseProofArgs = map[int16]string{
	1: "req",
}

type VerificationServiceGetPurchaseProofResult struct {
	Success *GetPurchaseProofResponse `thrift:"success,0,optional" frugal:"0,optional,GetPurchaseProofResponse" json:"success,omitempty"`
}

func NewVerificationServiceGetPurchaseProofResult() *VerificationServiceGetPurchaseProofResult {
	return &VerificationServiceGetPurchaseProofResult{}
}

func (p *VerificationServiceGetPurchaseProofResult) InitDefault() {
}

var VerificationServiceGetPurchaseProofResult_Success_DEFAULT *GetPurchaseProofResponse

func (p *VerificationServiceGetPurchaseProofResult) GetSuccess() (v *GetPurchaseProofResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceGetPurchaseProofResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceGetPurchaseProofResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPurchaseProofResponse)
}

func (p *VerificationServiceGetPurchaseProofResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceGetPurchaseProofResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetPurchaseProofResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetPurchaseProofResult = map[int16]string{
	0: "success",
}

type VerificationServiceVerifyXTweetArgs struct {
	Req *VerifyXTweetRequest `thrift:"req,1" frugal:"1,default,VerifyXTweetRequest" json:"req"`
}

func NewVerificationServiceVerifyXTweetArgs() *VerificationServiceVerifyXTweetArgs {
	return &VerificationServiceVerifyXTweetArgs{}
}

func (p *VerificationServiceVerifyXTweetArgs) InitDefault() {
}

var VerificationServiceVerifyXTweetArgs_Req_DEFAULT *VerifyXTweetRequest

func (p *VerificationServiceVerifyXTweetArgs) GetReq() (v *VerifyXTweetRequest) {
	if !p.IsSetReq() {
		return VerificationServiceVerifyXTweetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceVerifyXTweetArgs) SetReq(val *VerifyXTweetRequest) {
	p.Req = val
}

func (p *VerificationServiceVerifyXTweetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceVerifyXTweetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyXTweetArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyXTweetArgs = map[int16]string{
	1: "req",
}

type VerificationServiceVerifyXTweetResult struct {
	Success *VerifyXTweetResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyXTweetResponse" json:"success,omitempty"`
}

func NewVerificationServiceVerifyXTweetResult() *VerificationServiceVerifyXTweetResult {
	return &VerificationServiceVerifyXTweetResult{}
}

func (p *VerificationServiceVerifyXTweetResult) InitDefault() {
}

var VerificationServiceVerifyXTweetResult_Success_DEFAULT *VerifyXTweetResponse

func (p *VerificationServiceVerifyXTweetResult) GetSuccess() (v *VerifyXTweetResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceVerifyXTweetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceVerifyXTweetResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyXTweetResponse)
}

func (p *VerificationServiceVerifyXTweetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceVerifyXTweetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceVerifyXTweetResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceVerifyXTweetResult = map[int16]string{
	0: "success",
}

type VerificationServiceGetXVerificationStatusArgs struct {
	Req *GetXVerificationStatusRequest `thrift:"req,1" frugal:"1,default,GetXVerificationStatusRequest" json:"req"`
}

func NewVerificationServiceGetXVerificationStatusArgs() *VerificationServiceGetXVerificationStatusArgs {
	return &VerificationServiceGetXVerificationStatusArgs{}
}

func (p *VerificationServiceGetXVerificationStatusArgs) InitDefault() {
}

var VerificationServiceGetXVerificationStatusArgs_Req_DEFAULT *GetXVerificationStatusRequest

func (p *VerificationServiceGetXVerificationStatusArgs) GetReq() (v *GetXVerificationStatusRequest) {
	if !p.IsSetReq() {
		return VerificationServiceGetXVerificationStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VerificationServiceGetXVerificationStatusArgs) SetReq(val *GetXVerificationStatusRequest) {
	p.Req = val
}

func (p *VerificationServiceGetXVerificationStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerificationServiceGetXVerificationStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetXVerificationStatusArgs(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetXVerificationStatusArgs = map[int16]string{
	1: "req",
}

type VerificationServiceGetXVerificationStatusResult struct {
	Success *GetXVerificationStatusResponse `thrift:"success,0,optional" frugal:"0,optional,GetXVerificationStatusResponse" json:"success,omitempty"`
}

func NewVerificationServiceGetXVerificationStatusResult() *VerificationServiceGetXVerificationStatusResult {
	return &VerificationServiceGetXVerificationStatusResult{}
}

func (p *VerificationServiceGetXVerificationStatusResult) InitDefault() {
}

var VerificationServiceGetXVerificationStatusResult_Success_DEFAULT *GetXVerificationStatusResponse

func (p *VerificationServiceGetXVerificationStatusResult) GetSuccess() (v *GetXVerificationStatusResponse) {
	if !p.IsSetSuccess() {
		return VerificationServiceGetXVerificationStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VerificationServiceGetXVerificationStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetXVerificationStatusResponse)
}

func (p *VerificationServiceGetXVerificationStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerificationServiceGetXVerificationStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationServiceGetXVerificationStatusResult(%+v)", *p)
}

var fieldIDToName_VerificationServiceGetXVerificationStatusResult = map[int16]string{
	0: "success",
}
