// Code generated by Kitex v0.16.1. DO NOT EDIT.

package blockchainadapterservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	blockchain_adapter "github.com/stablepay/blockchain-adapter/kitex_gen/stablepay/blockchain_adapter"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"TransferStableCoin": kitex.NewMethodInfo(
		transferStableCoinHandler,
		newBlockchainAdapterServiceTransferStableCoinArgs,
		newBlockchainAdapterServiceTransferStableCoinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetBalance": kitex.NewMethodInfo(
		getBalanceHandler,
		newBlockchainAdapterServiceGetBalanceArgs,
		newBlockchainAdapterServiceGetBalanceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTxStatus": kitex.NewMethodInfo(
		getTxStatusHandler,
		newBlockchainAdapterServiceGetTxStatusArgs,
		newBlockchainAdapterServiceGetTxStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	blockchainAdapterServiceServiceInfo                = NewServiceInfo()
	blockchainAdapterServiceServiceInfoForClient       = NewServiceInfoForClient()
	blockchainAdapterServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return blockchainAdapterServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return blockchainAdapterServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return blockchainAdapterServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BlockchainAdapterService"
	handlerType := (*blockchain_adapter.BlockchainAdapterService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "blockchain_adapter",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func transferStableCoinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*blockchain_adapter.BlockchainAdapterServiceTransferStableCoinArgs)
	realResult := result.(*blockchain_adapter.BlockchainAdapterServiceTransferStableCoinResult)
	success, err := handler.(blockchain_adapter.BlockchainAdapterService).TransferStableCoin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBlockchainAdapterServiceTransferStableCoinArgs() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceTransferStableCoinArgs()
}

func newBlockchainAdapterServiceTransferStableCoinResult() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceTransferStableCoinResult()
}

func getBalanceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*blockchain_adapter.BlockchainAdapterServiceGetBalanceArgs)
	realResult := result.(*blockchain_adapter.BlockchainAdapterServiceGetBalanceResult)
	success, err := handler.(blockchain_adapter.BlockchainAdapterService).GetBalance(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBlockchainAdapterServiceGetBalanceArgs() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceGetBalanceArgs()
}

func newBlockchainAdapterServiceGetBalanceResult() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceGetBalanceResult()
}

func getTxStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*blockchain_adapter.BlockchainAdapterServiceGetTxStatusArgs)
	realResult := result.(*blockchain_adapter.BlockchainAdapterServiceGetTxStatusResult)
	success, err := handler.(blockchain_adapter.BlockchainAdapterService).GetTxStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBlockchainAdapterServiceGetTxStatusArgs() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceGetTxStatusArgs()
}

func newBlockchainAdapterServiceGetTxStatusResult() interface{} {
	return blockchain_adapter.NewBlockchainAdapterServiceGetTxStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TransferStableCoin(ctx context.Context, req *blockchain_adapter.TransferStableCoinRequest) (r *blockchain_adapter.TransferStableCoinResponse, err error) {
	var _args blockchain_adapter.BlockchainAdapterServiceTransferStableCoinArgs
	_args.Req = req
	var _result blockchain_adapter.BlockchainAdapterServiceTransferStableCoinResult
	if err = p.c.Call(ctx, "TransferStableCoin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBalance(ctx context.Context, req *blockchain_adapter.GetBalanceRequest) (r *blockchain_adapter.GetBalanceResponse, err error) {
	var _args blockchain_adapter.BlockchainAdapterServiceGetBalanceArgs
	_args.Req = req
	var _result blockchain_adapter.BlockchainAdapterServiceGetBalanceResult
	if err = p.c.Call(ctx, "GetBalance", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTxStatus(ctx context.Context, req *blockchain_adapter.GetTxStatusRequest) (r *blockchain_adapter.GetTxStatusResponse, err error) {
	var _args blockchain_adapter.BlockchainAdapterServiceGetTxStatusArgs
	_args.Req = req
	var _result blockchain_adapter.BlockchainAdapterServiceGetTxStatusResult
	if err = p.c.Call(ctx, "GetTxStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
