// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package payment_service

import (
	"context"
	"fmt"
	"stablepay/api-gateway/kitex_gen/stablepay/common"
)

type InitiatePaymentRequest struct {
	Base        *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid    common.DID      `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	SkillDid    common.DID      `thrift:"skill_did,3" frugal:"3,default,string" json:"skill_did"`
	AmountMinor int64           `thrift:"amount_minor,4" frugal:"4,default,i64" json:"amount_minor"`
	Currency    common.Currency `thrift:"currency,5" frugal:"5,default,Currency" json:"currency"`
	Signature   *string         `thrift:"signature,6,optional" frugal:"6,optional,string" json:"signature,omitempty"`
	Timestamp   *string         `thrift:"timestamp,7,optional" frugal:"7,optional,string" json:"timestamp,omitempty"`
}

func NewInitiatePaymentRequest() *InitiatePaymentRequest {
	return &InitiatePaymentRequest{}
}

func (p *InitiatePaymentRequest) InitDefault() {
}

var InitiatePaymentRequest_Base_DEFAULT *common.BaseReq

func (p *InitiatePaymentRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return InitiatePaymentRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *InitiatePaymentRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

func (p *InitiatePaymentRequest) GetSkillDid() (v common.DID) {
	return p.SkillDid
}

func (p *InitiatePaymentRequest) GetAmountMinor() (v int64) {
	return p.AmountMinor
}

func (p *InitiatePaymentRequest) GetCurrency() (v common.Currency) {
	return p.Currency
}

var InitiatePaymentRequest_Signature_DEFAULT string

func (p *InitiatePaymentRequest) GetSignature() (v string) {
	if !p.IsSetSignature() {
		return InitiatePaymentRequest_Signature_DEFAULT
	}
	return *p.Signature
}

var InitiatePaymentRequest_Timestamp_DEFAULT string

func (p *InitiatePaymentRequest) GetTimestamp() (v string) {
	if !p.IsSetTimestamp() {
		return InitiatePaymentRequest_Timestamp_DEFAULT
	}
	return *p.Timestamp
}
func (p *InitiatePaymentRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *InitiatePaymentRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *InitiatePaymentRequest) SetSkillDid(val common.DID) {
	p.SkillDid = val
}
func (p *InitiatePaymentRequest) SetAmountMinor(val int64) {
	p.AmountMinor = val
}
func (p *InitiatePaymentRequest) SetCurrency(val common.Currency) {
	p.Currency = val
}
func (p *InitiatePaymentRequest) SetSignature(val *string) {
	p.Signature = val
}
func (p *InitiatePaymentRequest) SetTimestamp(val *string) {
	p.Timestamp = val
}

func (p *InitiatePaymentRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *InitiatePaymentRequest) IsSetSignature() bool {
	return p.Signature != nil
}

func (p *InitiatePaymentRequest) IsSetTimestamp() bool {
	return p.Timestamp != nil
}

func (p *InitiatePaymentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitiatePaymentRequest(%+v)", *p)
}

var fieldIDToName_InitiatePaymentRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "skill_did",
	4: "amount_minor",
	5: "currency",
	6: "signature",
	7: "timestamp",
}

type InitiatePaymentResponse struct {
	Base        *common.BaseResp     `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	TxId        common.TxId          `thrift:"tx_id,2" frugal:"2,default,string" json:"tx_id"`
	TxHash      common.TxHash        `thrift:"tx_hash,3" frugal:"3,default,string" json:"tx_hash"`
	Status      common.PaymentStatus `thrift:"status,4" frugal:"4,default,PaymentStatus" json:"status"`
	CreatedAt   string               `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
	ConfirmedAt *string              `thrift:"confirmed_at,6,optional" frugal:"6,optional,string" json:"confirmed_at,omitempty"`
	FailedAt    *string              `thrift:"failed_at,7,optional" frugal:"7,optional,string" json:"failed_at,omitempty"`
}

func NewInitiatePaymentResponse() *InitiatePaymentResponse {
	return &InitiatePaymentResponse{}
}

func (p *InitiatePaymentResponse) InitDefault() {
}

var InitiatePaymentResponse_Base_DEFAULT *common.BaseResp

func (p *InitiatePaymentResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return InitiatePaymentResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *InitiatePaymentResponse) GetTxId() (v common.TxId) {
	return p.TxId
}

func (p *InitiatePaymentResponse) GetTxHash() (v common.TxHash) {
	return p.TxHash
}

func (p *InitiatePaymentResponse) GetStatus() (v common.PaymentStatus) {
	return p.Status
}

func (p *InitiatePaymentResponse) GetCreatedAt() (v string) {
	return p.CreatedAt
}

var InitiatePaymentResponse_ConfirmedAt_DEFAULT string

func (p *InitiatePaymentResponse) GetConfirmedAt() (v string) {
	if !p.IsSetConfirmedAt() {
		return InitiatePaymentResponse_ConfirmedAt_DEFAULT
	}
	return *p.ConfirmedAt
}

var InitiatePaymentResponse_FailedAt_DEFAULT string

func (p *InitiatePaymentResponse) GetFailedAt() (v string) {
	if !p.IsSetFailedAt() {
		return InitiatePaymentResponse_FailedAt_DEFAULT
	}
	return *p.FailedAt
}
func (p *InitiatePaymentResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *InitiatePaymentResponse) SetTxId(val common.TxId) {
	p.TxId = val
}
func (p *InitiatePaymentResponse) SetTxHash(val common.TxHash) {
	p.TxHash = val
}
func (p *InitiatePaymentResponse) SetStatus(val common.PaymentStatus) {
	p.Status = val
}
func (p *InitiatePaymentResponse) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *InitiatePaymentResponse) SetConfirmedAt(val *string) {
	p.ConfirmedAt = val
}
func (p *InitiatePaymentResponse) SetFailedAt(val *string) {
	p.FailedAt = val
}

func (p *InitiatePaymentResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *InitiatePaymentResponse) IsSetConfirmedAt() bool {
	return p.ConfirmedAt != nil
}

func (p *InitiatePaymentResponse) IsSetFailedAt() bool {
	return p.FailedAt != nil
}

func (p *InitiatePaymentResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitiatePaymentResponse(%+v)", *p)
}

var fieldIDToName_InitiatePaymentResponse = map[int16]string{
	1: "base",
	2: "tx_id",
	3: "tx_hash",
	4: "status",
	5: "created_at",
	6: "confirmed_at",
	7: "failed_at",
}

type GetPaymentStatusRequest struct {
	Base *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	TxId common.TxId     `thrift:"tx_id,2" frugal:"2,default,string" json:"tx_id"`
}

func NewGetPaymentStatusRequest() *GetPaymentStatusRequest {
	return &GetPaymentStatusRequest{}
}

func (p *GetPaymentStatusRequest) InitDefault() {
}

var GetPaymentStatusRequest_Base_DEFAULT *common.BaseReq

func (p *GetPaymentStatusRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetPaymentStatusRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPaymentStatusRequest) GetTxId() (v common.TxId) {
	return p.TxId
}
func (p *GetPaymentStatusRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetPaymentStatusRequest) SetTxId(val common.TxId) {
	p.TxId = val
}

func (p *GetPaymentStatusRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPaymentStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPaymentStatusRequest(%+v)", *p)
}

var fieldIDToName_GetPaymentStatusRequest = map[int16]string{
	1: "base",
	2: "tx_id",
}

type GetPaymentStatusResponse struct {
	Base        *common.BaseResp     `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	TxId        common.TxId          `thrift:"tx_id,2" frugal:"2,default,string" json:"tx_id"`
	Status      common.PaymentStatus `thrift:"status,3" frugal:"3,default,PaymentStatus" json:"status"`
	TxHash      *common.TxHash       `thrift:"tx_hash,4,optional" frugal:"4,optional,string" json:"tx_hash,omitempty"`
	ConfirmedAt *string              `thrift:"confirmed_at,5,optional" frugal:"5,optional,string" json:"confirmed_at,omitempty"`
	FailedAt    *string              `thrift:"failed_at,6,optional" frugal:"6,optional,string" json:"failed_at,omitempty"`
}

func NewGetPaymentStatusResponse() *GetPaymentStatusResponse {
	return &GetPaymentStatusResponse{}
}

func (p *GetPaymentStatusResponse) InitDefault() {
}

var GetPaymentStatusResponse_Base_DEFAULT *common.BaseResp

func (p *GetPaymentStatusResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetPaymentStatusResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPaymentStatusResponse) GetTxId() (v common.TxId) {
	return p.TxId
}

func (p *GetPaymentStatusResponse) GetStatus() (v common.PaymentStatus) {
	return p.Status
}

var GetPaymentStatusResponse_TxHash_DEFAULT common.TxHash

func (p *GetPaymentStatusResponse) GetTxHash() (v common.TxHash) {
	if !p.IsSetTxHash() {
		return GetPaymentStatusResponse_TxHash_DEFAULT
	}
	return *p.TxHash
}

var GetPaymentStatusResponse_ConfirmedAt_DEFAULT string

func (p *GetPaymentStatusResponse) GetConfirmedAt() (v string) {
	if !p.IsSetConfirmedAt() {
		return GetPaymentStatusResponse_ConfirmedAt_DEFAULT
	}
	return *p.ConfirmedAt
}

var GetPaymentStatusResponse_FailedAt_DEFAULT string

func (p *GetPaymentStatusResponse) GetFailedAt() (v string) {
	if !p.IsSetFailedAt() {
		return GetPaymentStatusResponse_FailedAt_DEFAULT
	}
	return *p.FailedAt
}
func (p *GetPaymentStatusResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetPaymentStatusResponse) SetTxId(val common.TxId) {
	p.TxId = val
}
func (p *GetPaymentStatusResponse) SetStatus(val common.PaymentStatus) {
	p.Status = val
}
func (p *GetPaymentStatusResponse) SetTxHash(val *common.TxHash) {
	p.TxHash = val
}
func (p *GetPaymentStatusResponse) SetConfirmedAt(val *string) {
	p.ConfirmedAt = val
}
func (p *GetPaymentStatusResponse) SetFailedAt(val *string) {
	p.FailedAt = val
}

func (p *GetPaymentStatusResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPaymentStatusResponse) IsSetTxHash() bool {
	return p.TxHash != nil
}

func (p *GetPaymentStatusResponse) IsSetConfirmedAt() bool {
	return p.ConfirmedAt != nil
}

func (p *GetPaymentStatusResponse) IsSetFailedAt() bool {
	return p.FailedAt != nil
}

func (p *GetPaymentStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPaymentStatusResponse(%+v)", *p)
}

var fieldIDToName_GetPaymentStatusResponse = map[int16]string{
	1: "base",
	2: "tx_id",
	3: "status",
	4: "tx_hash",
	5: "confirmed_at",
	6: "failed_at",
}

type PaymentHistoryItem struct {
	TxId        common.TxId          `thrift:"tx_id,1" frugal:"1,default,string" json:"tx_id"`
	SkillDid    common.DID           `thrift:"skill_did,2" frugal:"2,default,string" json:"skill_did"`
	AmountMinor int64                `thrift:"amount_minor,3" frugal:"3,default,i64" json:"amount_minor"`
	Currency    common.Currency      `thrift:"currency,4" frugal:"4,default,Currency" json:"currency"`
	Status      common.PaymentStatus `thrift:"status,5" frugal:"5,default,PaymentStatus" json:"status"`
	CreatedAt   string               `thrift:"created_at,6" frugal:"6,default,string" json:"created_at"`
}

func NewPaymentHistoryItem() *PaymentHistoryItem {
	return &PaymentHistoryItem{}
}

func (p *PaymentHistoryItem) InitDefault() {
}

func (p *PaymentHistoryItem) GetTxId() (v common.TxId) {
	return p.TxId
}

func (p *PaymentHistoryItem) GetSkillDid() (v common.DID) {
	return p.SkillDid
}

func (p *PaymentHistoryItem) GetAmountMinor() (v int64) {
	return p.AmountMinor
}

func (p *PaymentHistoryItem) GetCurrency() (v common.Currency) {
	return p.Currency
}

func (p *PaymentHistoryItem) GetStatus() (v common.PaymentStatus) {
	return p.Status
}

func (p *PaymentHistoryItem) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *PaymentHistoryItem) SetTxId(val common.TxId) {
	p.TxId = val
}
func (p *PaymentHistoryItem) SetSkillDid(val common.DID) {
	p.SkillDid = val
}
func (p *PaymentHistoryItem) SetAmountMinor(val int64) {
	p.AmountMinor = val
}
func (p *PaymentHistoryItem) SetCurrency(val common.Currency) {
	p.Currency = val
}
func (p *PaymentHistoryItem) SetStatus(val common.PaymentStatus) {
	p.Status = val
}
func (p *PaymentHistoryItem) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *PaymentHistoryItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentHistoryItem(%+v)", *p)
}

var fieldIDToName_PaymentHistoryItem = map[int16]string{
	1: "tx_id",
	2: "skill_did",
	3: "amount_minor",
	4: "currency",
	5: "status",
	6: "created_at",
}

type ListPaymentHistoryRequest struct {
	Base     *common.BaseReq     `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	AgentDid common.DID          `thrift:"agent_did,2" frugal:"2,default,string" json:"agent_did"`
	Page     *common.PageRequest `thrift:"page,3" frugal:"3,default,common.PageRequest" json:"page"`
}

func NewListPaymentHistoryRequest() *ListPaymentHistoryRequest {
	return &ListPaymentHistoryRequest{}
}

func (p *ListPaymentHistoryRequest) InitDefault() {
}

var ListPaymentHistoryRequest_Base_DEFAULT *common.BaseReq

func (p *ListPaymentHistoryRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return ListPaymentHistoryRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *ListPaymentHistoryRequest) GetAgentDid() (v common.DID) {
	return p.AgentDid
}

var ListPaymentHistoryRequest_Page_DEFAULT *common.PageRequest

func (p *ListPaymentHistoryRequest) GetPage() (v *common.PageRequest) {
	if !p.IsSetPage() {
		return ListPaymentHistoryRequest_Page_DEFAULT
	}
	return p.Page
}
func (p *ListPaymentHistoryRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *ListPaymentHistoryRequest) SetAgentDid(val common.DID) {
	p.AgentDid = val
}
func (p *ListPaymentHistoryRequest) SetPage(val *common.PageRequest) {
	p.Page = val
}

func (p *ListPaymentHistoryRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListPaymentHistoryRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListPaymentHistoryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPaymentHistoryRequest(%+v)", *p)
}

var fieldIDToName_ListPaymentHistoryRequest = map[int16]string{
	1: "base",
	2: "agent_did",
	3: "page",
}

type ListPaymentHistoryResponse struct {
	Base  *common.BaseResp      `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Items []*PaymentHistoryItem `thrift:"items,2" frugal:"2,default,list<PaymentHistoryItem>" json:"items"`
	Page  *common.PageResult_   `thrift:"page,3" frugal:"3,default,common.PageResult_" json:"page"`
}

func NewListPaymentHistoryResponse() *ListPaymentHistoryResponse {
	return &ListPaymentHistoryResponse{}
}

func (p *ListPaymentHistoryResponse) InitDefault() {
}

var ListPaymentHistoryResponse_Base_DEFAULT *common.BaseResp

func (p *ListPaymentHistoryResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListPaymentHistoryResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *ListPaymentHistoryResponse) GetItems() (v []*PaymentHistoryItem) {
	return p.Items
}

var ListPaymentHistoryResponse_Page_DEFAULT *common.PageResult_

func (p *ListPaymentHistoryResponse) GetPage() (v *common.PageResult_) {
	if !p.IsSetPage() {
		return ListPaymentHistoryResponse_Page_DEFAULT
	}
	return p.Page
}
func (p *ListPaymentHistoryResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListPaymentHistoryResponse) SetItems(val []*PaymentHistoryItem) {
	p.Items = val
}
func (p *ListPaymentHistoryResponse) SetPage(val *common.PageResult_) {
	p.Page = val
}

func (p *ListPaymentHistoryResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListPaymentHistoryResponse) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListPaymentHistoryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPaymentHistoryResponse(%+v)", *p)
}

var fieldIDToName_ListPaymentHistoryResponse = map[int16]string{
	1: "base",
	2: "items",
	3: "page",
}

type PaymentService interface {
	InitiatePayment(ctx context.Context, req *InitiatePaymentRequest) (r *InitiatePaymentResponse, err error)

	GetPaymentStatus(ctx context.Context, req *GetPaymentStatusRequest) (r *GetPaymentStatusResponse, err error)

	ListPaymentHistory(ctx context.Context, req *ListPaymentHistoryRequest) (r *ListPaymentHistoryResponse, err error)
}

type PaymentServiceInitiatePaymentArgs struct {
	Req *InitiatePaymentRequest `thrift:"req,1" frugal:"1,default,InitiatePaymentRequest" json:"req"`
}

func NewPaymentServiceInitiatePaymentArgs() *PaymentServiceInitiatePaymentArgs {
	return &PaymentServiceInitiatePaymentArgs{}
}

func (p *PaymentServiceInitiatePaymentArgs) InitDefault() {
}

var PaymentServiceInitiatePaymentArgs_Req_DEFAULT *InitiatePaymentRequest

func (p *PaymentServiceInitiatePaymentArgs) GetReq() (v *InitiatePaymentRequest) {
	if !p.IsSetReq() {
		return PaymentServiceInitiatePaymentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceInitiatePaymentArgs) SetReq(val *InitiatePaymentRequest) {
	p.Req = val
}

func (p *PaymentServiceInitiatePaymentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceInitiatePaymentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceInitiatePaymentArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceInitiatePaymentArgs = map[int16]string{
	1: "req",
}

type PaymentServiceInitiatePaymentResult struct {
	Success *InitiatePaymentResponse `thrift:"success,0,optional" frugal:"0,optional,InitiatePaymentResponse" json:"success,omitempty"`
}

func NewPaymentServiceInitiatePaymentResult() *PaymentServiceInitiatePaymentResult {
	return &PaymentServiceInitiatePaymentResult{}
}

func (p *PaymentServiceInitiatePaymentResult) InitDefault() {
}

var PaymentServiceInitiatePaymentResult_Success_DEFAULT *InitiatePaymentResponse

func (p *PaymentServiceInitiatePaymentResult) GetSuccess() (v *InitiatePaymentResponse) {
	if !p.IsSetSuccess() {
		return PaymentServiceInitiatePaymentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceInitiatePaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*InitiatePaymentResponse)
}

func (p *PaymentServiceInitiatePaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceInitiatePaymentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceInitiatePaymentResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceInitiatePaymentResult = map[int16]string{
	0: "success",
}

type PaymentServiceGetPaymentStatusArgs struct {
	Req *GetPaymentStatusRequest `thrift:"req,1" frugal:"1,default,GetPaymentStatusRequest" json:"req"`
}

func NewPaymentServiceGetPaymentStatusArgs() *PaymentServiceGetPaymentStatusArgs {
	return &PaymentServiceGetPaymentStatusArgs{}
}

func (p *PaymentServiceGetPaymentStatusArgs) InitDefault() {
}

var PaymentServiceGetPaymentStatusArgs_Req_DEFAULT *GetPaymentStatusRequest

func (p *PaymentServiceGetPaymentStatusArgs) GetReq() (v *GetPaymentStatusRequest) {
	if !p.IsSetReq() {
		return PaymentServiceGetPaymentStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceGetPaymentStatusArgs) SetReq(val *GetPaymentStatusRequest) {
	p.Req = val
}

func (p *PaymentServiceGetPaymentStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceGetPaymentStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetPaymentStatusArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetPaymentStatusArgs = map[int16]string{
	1: "req",
}

type PaymentServiceGetPaymentStatusResult struct {
	Success *GetPaymentStatusResponse `thrift:"success,0,optional" frugal:"0,optional,GetPaymentStatusResponse" json:"success,omitempty"`
}

func NewPaymentServiceGetPaymentStatusResult() *PaymentServiceGetPaymentStatusResult {
	return &PaymentServiceGetPaymentStatusResult{}
}

func (p *PaymentServiceGetPaymentStatusResult) InitDefault() {
}

var PaymentServiceGetPaymentStatusResult_Success_DEFAULT *GetPaymentStatusResponse

func (p *PaymentServiceGetPaymentStatusResult) GetSuccess() (v *GetPaymentStatusResponse) {
	if !p.IsSetSuccess() {
		return PaymentServiceGetPaymentStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceGetPaymentStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPaymentStatusResponse)
}

func (p *PaymentServiceGetPaymentStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceGetPaymentStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetPaymentStatusResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetPaymentStatusResult = map[int16]string{
	0: "success",
}

type PaymentServiceListPaymentHistoryArgs struct {
	Req *ListPaymentHistoryRequest `thrift:"req,1" frugal:"1,default,ListPaymentHistoryRequest" json:"req"`
}

func NewPaymentServiceListPaymentHistoryArgs() *PaymentServiceListPaymentHistoryArgs {
	return &PaymentServiceListPaymentHistoryArgs{}
}

func (p *PaymentServiceListPaymentHistoryArgs) InitDefault() {
}

var PaymentServiceListPaymentHistoryArgs_Req_DEFAULT *ListPaymentHistoryRequest

func (p *PaymentServiceListPaymentHistoryArgs) GetReq() (v *ListPaymentHistoryRequest) {
	if !p.IsSetReq() {
		return PaymentServiceListPaymentHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceListPaymentHistoryArgs) SetReq(val *ListPaymentHistoryRequest) {
	p.Req = val
}

func (p *PaymentServiceListPaymentHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceListPaymentHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceListPaymentHistoryArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceListPaymentHistoryArgs = map[int16]string{
	1: "req",
}

type PaymentServiceListPaymentHistoryResult struct {
	Success *ListPaymentHistoryResponse `thrift:"success,0,optional" frugal:"0,optional,ListPaymentHistoryResponse" json:"success,omitempty"`
}

func NewPaymentServiceListPaymentHistoryResult() *PaymentServiceListPaymentHistoryResult {
	return &PaymentServiceListPaymentHistoryResult{}
}

func (p *PaymentServiceListPaymentHistoryResult) InitDefault() {
}

var PaymentServiceListPaymentHistoryResult_Success_DEFAULT *ListPaymentHistoryResponse

func (p *PaymentServiceListPaymentHistoryResult) GetSuccess() (v *ListPaymentHistoryResponse) {
	if !p.IsSetSuccess() {
		return PaymentServiceListPaymentHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceListPaymentHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPaymentHistoryResponse)
}

func (p *PaymentServiceListPaymentHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceListPaymentHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceListPaymentHistoryResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceListPaymentHistoryResult = map[int16]string{
	0: "success",
}
