apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stablepay-dev
resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - infra.yaml
  - mysql-init-job.yaml
  - services.yaml
