-- S2 runtime persistence. No catalog, memory, retrieval, workflow or vector tables.
CREATE TABLE IF NOT EXISTS commerce_episodes (
    episode_id                 VARCHAR(128) NOT NULL PRIMARY KEY,
    request_id                 VARCHAR(128) NOT NULL,
    requester_did              VARCHAR(128) NOT NULL,
    session_id                 VARCHAR(128) NULL,
    state                      VARCHAR(32) NOT NULL,
    terminal_reason            VARCHAR(128) NULL,
    contract_snapshot_hash     CHAR(71) NOT NULL,
    contract_snapshot          LONGTEXT NOT NULL,
    selected_merchant_did      VARCHAR(128) NULL,
    selected_capability_id     VARCHAR(128) NULL,
    selected_workflow_version  VARCHAR(64) NULL,
    current_quote_hash         CHAR(71) NULL,
    entitlement_refs           JSON NULL,
    delivery_refs              JSON NULL,
    validation_evidence_refs   JSON NULL,
    attempted_merchants        JSON NULL,
    action_count               INT NOT NULL DEFAULT 0,
    payment_attempt_count      INT NOT NULL DEFAULT 0,
    delivery_attempt_count     INT NOT NULL DEFAULT 0,
    retry_count                INT NOT NULL DEFAULT 0,
    max_total_attempts         INT NOT NULL,
    max_payment_attempts       INT NOT NULL,
    max_delivery_attempts      INT NOT NULL,
    budget_currency             VARCHAR(16) NOT NULL,
    budget_limit_minor         BIGINT NOT NULL,
    reserved_amount             BIGINT NOT NULL DEFAULT 0,
    settled_amount              BIGINT NOT NULL DEFAULT 0,
    refunded_amount             BIGINT NOT NULL DEFAULT 0,
    consumed_amount             BIGINT NOT NULL DEFAULT 0,
    available_budget            BIGINT NOT NULL,
    sunk_cost                   BIGINT NOT NULL DEFAULT 0,
    refund_reusable              BOOLEAN NOT NULL DEFAULT TRUE,
    deadline_at                 DATETIME(6) NOT NULL,
    version                     BIGINT UNSIGNED NOT NULL,
    created_at                  DATETIME(6) NOT NULL,
    updated_at                  DATETIME(6) NOT NULL,
    UNIQUE KEY uk_commerce_episode_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS episode_events (
    event_id                   VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    sequence                   BIGINT UNSIGNED NOT NULL,
    occurred_at                DATETIME(6) NOT NULL,
    state_before               VARCHAR(32) NOT NULL,
    action_payload             JSON NOT NULL,
    observation_payload       JSON NOT NULL,
    decision_payload           JSON NOT NULL,
    runtime_verdict_payload   JSON NOT NULL,
    state_after                VARCHAR(32) NOT NULL,
    actor                      VARCHAR(32) NOT NULL,
    trace_id                   VARCHAR(128) NULL,
    runtime_version            VARCHAR(64) NOT NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    UNIQUE KEY uk_episode_sequence (episode_id, sequence),
    UNIQUE KEY uk_episode_idempotency (episode_id, idempotency_key),
    CONSTRAINT fk_episode_events_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ledger_entries (
    entry_id                   VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    sequence                   BIGINT UNSIGNED NOT NULL,
    type                       VARCHAR(40) NOT NULL,
    currency                   VARCHAR(16) NOT NULL,
    amount_minor               BIGINT NOT NULL,
    payment_intent_id          VARCHAR(128) NULL,
    tx_id                      VARCHAR(128) NULL,
    refund_id                  VARCHAR(128) NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    occurred_at                DATETIME(6) NOT NULL,
    trace_id                   VARCHAR(128) NULL,
    reference_hash             CHAR(71) NOT NULL,
    metadata_hash              CHAR(71) NULL,
    UNIQUE KEY uk_ledger_sequence (episode_id, sequence),
    UNIQUE KEY uk_ledger_idempotency (episode_id, idempotency_key),
    KEY idx_ledger_intent (payment_intent_id),
    KEY idx_ledger_tx (tx_id),
    CONSTRAINT fk_ledger_entries_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_intents (
    intent_id                  VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    merchant_did               VARCHAR(128) NOT NULL,
    capability_id              VARCHAR(128) NOT NULL,
    payee_did                  VARCHAR(128) NOT NULL,
    quote_hash                 CHAR(71) NOT NULL,
    amount_minor               BIGINT NOT NULL,
    currency                   VARCHAR(16) NOT NULL,
    requester_did              VARCHAR(128) NOT NULL,
    episode_version            BIGINT UNSIGNED NOT NULL,
    budget_reservation         BIGINT NOT NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    economic_key               CHAR(71) NOT NULL,
    expires_at                 DATETIME(6) NOT NULL,
    status                     VARCHAR(24) NOT NULL,
    tx_id                      VARCHAR(128) NULL,
    tx_hash                    VARCHAR(128) NULL,
    authorization_ref          VARCHAR(128) NULL,
    credential_ref             VARCHAR(128) NOT NULL,
    request_fingerprint        CHAR(71) NOT NULL,
    failure_code               VARCHAR(128) NULL,
    created_at                 DATETIME(6) NOT NULL,
    updated_at                 DATETIME(6) NOT NULL,
    UNIQUE KEY uk_intent_idempotency (episode_id, idempotency_key),
    UNIQUE KEY uk_intent_economic (episode_id, economic_key),
    KEY idx_intent_episode (episode_id),
    CONSTRAINT fk_payment_intents_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
