-- S2 runtime persistence. No catalog, memory, retrieval, workflow or vector tables.
CREATE TABLE IF NOT EXISTS commerce_episodes (
    episode_id                 VARCHAR(128) NOT NULL PRIMARY KEY,
    request_id                 VARCHAR(128) NOT NULL,
    requester_did              VARCHAR(128) NOT NULL,
    session_id                 VARCHAR(128) NULL,
    state                      VARCHAR(32) NOT NULL,
    terminal_reason            VARCHAR(128) NULL,
    contract_snapshot_hash     CHAR(71) NOT NULL,
    contract_snapshot          LONGTEXT NOT NULL,
    selected_merchant_did      VARCHAR(128) NULL,
    selected_capability_id     VARCHAR(128) NULL,
    selected_candidate_set_id  VARCHAR(128) NULL,
    selected_catalog_version   VARCHAR(64) NULL,
    selected_catalog_snapshot_hash CHAR(71) NULL,
    selected_catalog_snapshot_ref VARCHAR(255) NULL,
    selected_workflow_version  VARCHAR(64) NULL,
    current_quote_hash         CHAR(71) NULL,
    entitlement_refs           JSON NULL,
    delivery_refs              JSON NULL,
    validation_evidence_refs   JSON NULL,
    attempted_merchants        JSON NULL,
    action_count               INT NOT NULL DEFAULT 0,
    payment_attempt_count      INT NOT NULL DEFAULT 0,
    delivery_attempt_count     INT NOT NULL DEFAULT 0,
    retry_count                INT NOT NULL DEFAULT 0,
    max_total_attempts         INT NOT NULL,
    max_payment_attempts       INT NOT NULL,
    max_delivery_attempts      INT NOT NULL,
    budget_currency             VARCHAR(16) NOT NULL,
    budget_limit_minor         BIGINT NOT NULL,
    reserved_amount             BIGINT NOT NULL DEFAULT 0,
    settled_amount              BIGINT NOT NULL DEFAULT 0,
    refunded_amount             BIGINT NOT NULL DEFAULT 0,
    consumed_amount             BIGINT NOT NULL DEFAULT 0,
    available_budget            BIGINT NOT NULL,
    sunk_cost                   BIGINT NOT NULL DEFAULT 0,
    refund_reusable              BOOLEAN NOT NULL DEFAULT TRUE,
    deadline_at                 DATETIME(6) NOT NULL,
    version                     BIGINT UNSIGNED NOT NULL,
    created_at                  DATETIME(6) NOT NULL,
    updated_at                  DATETIME(6) NOT NULL,
    UNIQUE KEY uk_commerce_episode_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS episode_events (
    event_id                   VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    sequence                   BIGINT UNSIGNED NOT NULL,
    occurred_at                DATETIME(6) NOT NULL,
    state_before               VARCHAR(32) NOT NULL,
    action_payload             JSON NOT NULL,
    observation_payload       JSON NOT NULL,
    decision_payload           JSON NOT NULL,
    runtime_verdict_payload   JSON NOT NULL,
    state_after                VARCHAR(32) NOT NULL,
    actor                      VARCHAR(32) NOT NULL,
    trace_id                   VARCHAR(128) NULL,
    runtime_version            VARCHAR(64) NOT NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    UNIQUE KEY uk_episode_sequence (episode_id, sequence),
    UNIQUE KEY uk_episode_idempotency (episode_id, idempotency_key),
    CONSTRAINT fk_episode_events_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ledger_entries (
    entry_id                   VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    sequence                   BIGINT UNSIGNED NOT NULL,
    type                       VARCHAR(40) NOT NULL,
    currency                   VARCHAR(16) NOT NULL,
    amount_minor               BIGINT NOT NULL,
    payment_intent_id          VARCHAR(128) NULL,
    tx_id                      VARCHAR(128) NULL,
    refund_id                  VARCHAR(128) NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    occurred_at                DATETIME(6) NOT NULL,
    trace_id                   VARCHAR(128) NULL,
    reference_hash             CHAR(71) NOT NULL,
    metadata_hash              CHAR(71) NULL,
    UNIQUE KEY uk_ledger_sequence (episode_id, sequence),
    UNIQUE KEY uk_ledger_idempotency (episode_id, idempotency_key),
    KEY idx_ledger_intent (payment_intent_id),
    KEY idx_ledger_tx (tx_id),
    CONSTRAINT fk_ledger_entries_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_intents (
    intent_id                  VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                 VARCHAR(128) NOT NULL,
    merchant_did               VARCHAR(128) NOT NULL,
    capability_id              VARCHAR(128) NOT NULL,
    payee_did                  VARCHAR(128) NOT NULL,
    quote_hash                 CHAR(71) NOT NULL,
    amount_minor               BIGINT NOT NULL,
    currency                   VARCHAR(16) NOT NULL,
    requester_did              VARCHAR(128) NOT NULL,
    episode_version            BIGINT UNSIGNED NOT NULL,
    budget_reservation         BIGINT NOT NULL,
    idempotency_key            VARCHAR(128) NOT NULL,
    economic_key               CHAR(71) NOT NULL,
    expires_at                 DATETIME(6) NOT NULL,
    status                     VARCHAR(24) NOT NULL,
    tx_id                      VARCHAR(128) NULL,
    tx_hash                    VARCHAR(128) NULL,
    authorization_ref          VARCHAR(128) NULL,
    credential_ref             VARCHAR(128) NOT NULL,
    request_fingerprint        CHAR(71) NOT NULL,
    failure_code               VARCHAR(128) NULL,
    created_at                 DATETIME(6) NOT NULL,
    updated_at                 DATETIME(6) NOT NULL,
    UNIQUE KEY uk_intent_idempotency (episode_id, idempotency_key),
    UNIQUE KEY uk_intent_economic (episode_id, economic_key),
    KEY idx_intent_episode (episode_id),
    CONSTRAINT fk_payment_intents_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- S3 trusted catalog versions. Each row is immutable; the current table is
-- only a pointer used to expose the active version for structured discovery.
CREATE TABLE IF NOT EXISTS merchant_capabilities (
    merchant_did                VARCHAR(128) NOT NULL,
    capability_id               VARCHAR(128) NOT NULL,
    catalog_version             VARCHAR(64) NOT NULL,
    payee_did                   VARCHAR(128) NOT NULL,
    name                        VARCHAR(255) NOT NULL,
    description                 TEXT NOT NULL,
    task_types                  JSON NOT NULL,
    semantic_tags               JSON NOT NULL,
    invoke_endpoint             JSON NOT NULL,
    quote_endpoint              JSON NULL,
    input_schema_ref            VARCHAR(255) NOT NULL,
    output_schema_ref           VARCHAR(255) NOT NULL,
    input_content_types         JSON NOT NULL,
    output_content_types        JSON NOT NULL,
    supported_protocol_versions JSON NOT NULL,
    supported_currencies        JSON NOT NULL,
    pricing_model               VARCHAR(64) NOT NULL,
    price_hint_minor            BIGINT NULL,
    price_hint_currency         VARCHAR(16) NULL,
    status                      VARCHAR(24) NOT NULL,
    availability                VARCHAR(24) NOT NULL,
    source                      VARCHAR(128) NOT NULL,
    source_ref                  VARCHAR(255) NULL,
    source_hash                 CHAR(71) NULL,
    valid_from                  DATETIME(6) NOT NULL,
    valid_until                 DATETIME(6) NOT NULL,
    created_at                  DATETIME(6) NOT NULL,
    updated_at                  DATETIME(6) NOT NULL,
    PRIMARY KEY (merchant_did, capability_id, catalog_version),
    KEY idx_capability_current_lookup (merchant_did, capability_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS merchant_capability_current (
    merchant_did                VARCHAR(128) NOT NULL,
    capability_id               VARCHAR(128) NOT NULL,
    catalog_version             VARCHAR(64) NOT NULL,
    updated_at                  DATETIME(6) NOT NULL,
    PRIMARY KEY (merchant_did, capability_id),
    CONSTRAINT fk_capability_current_version FOREIGN KEY (merchant_did, capability_id, catalog_version)
        REFERENCES merchant_capabilities (merchant_did, capability_id, catalog_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS candidate_sets (
    candidate_set_id            VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id                  VARCHAR(128) NOT NULL,
    request_id                  VARCHAR(128) NOT NULL,
    query_hash                  CHAR(71) NOT NULL,
    catalog_snapshot_refs       JSON NOT NULL,
    candidates                  JSON NOT NULL,
    generated_at                DATETIME(6) NOT NULL,
    expires_at                  DATETIME(6) NOT NULL,
    facts_ref                   VARCHAR(255) NOT NULL,
    payload_hash                CHAR(71) NOT NULL,
    KEY idx_candidate_set_episode (episode_id),
    KEY idx_candidate_set_expiry (expires_at),
    CONSTRAINT fk_candidate_sets_episode FOREIGN KEY (episode_id)
        REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS merchant_invocations (
    invocation_id            VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id               VARCHAR(128) NOT NULL,
    merchant_did             VARCHAR(128) NOT NULL,
    capability_id            VARCHAR(128) NOT NULL,
    catalog_version          VARCHAR(64) NOT NULL,
    catalog_snapshot_hash    CHAR(71) NOT NULL,
    phase                    VARCHAR(16) NOT NULL,
    attempt                  INT NOT NULL,
    request_hash             CHAR(71) NOT NULL,
    response_status          INT NOT NULL DEFAULT 0,
    response_content_type    VARCHAR(255) NULL,
    response_payload_hash    CHAR(71) NULL,
    response_ref              VARCHAR(255) NULL,
    selected_headers         JSON NULL,
    response_body            LONGBLOB NULL,
    payment_required_ref     VARCHAR(255) NULL,
    entitlement_ref          VARCHAR(255) NULL,
    started_at               DATETIME(6) NOT NULL,
    completed_at             DATETIME(6) NULL,
    trace_id                 VARCHAR(128) NULL,
    idempotency_key          VARCHAR(255) NOT NULL,
    UNIQUE KEY uk_invocation_idempotency (episode_id, idempotency_key),
    KEY idx_invocation_episode (episode_id),
    CONSTRAINT fk_invocations_episode FOREIGN KEY (episode_id) REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_requirement_facts (
    payment_requirement_id   VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id               VARCHAR(128) NOT NULL,
    invocation_id            VARCHAR(128) NOT NULL,
    merchant_did             VARCHAR(128) NOT NULL,
    capability_id            VARCHAR(128) NOT NULL,
    catalog_version          VARCHAR(64) NOT NULL,
    catalog_snapshot_hash    CHAR(71) NOT NULL,
    protocol_version         VARCHAR(32) NOT NULL,
    scheme                   VARCHAR(32) NOT NULL,
    network                  VARCHAR(128) NOT NULL,
    asset                    VARCHAR(128) NOT NULL,
    atomic_amount            BIGINT NOT NULL,
    atomic_decimals          INT NOT NULL,
    business_amount_minor    BIGINT NOT NULL,
    currency                 VARCHAR(16) NOT NULL,
    pay_to                   VARCHAR(128) NOT NULL,
    payee_did                VARCHAR(128) NOT NULL,
    resource_url             VARCHAR(1024) NOT NULL,
    product_id               VARCHAR(255) NULL,
    skill_did                VARCHAR(255) NULL,
    max_timeout_seconds      INT NOT NULL,
    observed_at              DATETIME(6) NOT NULL,
    expires_at                DATETIME(6) NOT NULL,
    raw_payload_hash         CHAR(71) NOT NULL,
    canonical_quote_hash     CHAR(71) NOT NULL,
    facts_ref                VARCHAR(255) NOT NULL,
    UNIQUE KEY uk_requirement_invocation (episode_id, invocation_id),
    CONSTRAINT fk_requirements_episode FOREIGN KEY (episode_id) REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS delivery_artifacts (
    delivery_id              VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id               VARCHAR(128) NOT NULL,
    invocation_id            VARCHAR(128) NOT NULL,
    merchant_did             VARCHAR(128) NOT NULL,
    capability_id            VARCHAR(128) NOT NULL,
    content_type             VARCHAR(255) NULL,
    payload_ref              VARCHAR(255) NOT NULL,
    payload_hash             CHAR(71) NOT NULL,
    body                     LONGBLOB NULL,
    payment_intent_id        VARCHAR(128) NULL,
    entitlement_ref          VARCHAR(255) NULL,
    attempt                  INT NOT NULL,
    http_status              INT NOT NULL,
    received_at              DATETIME(6) NOT NULL,
    KEY idx_delivery_episode (episode_id),
    CONSTRAINT fk_delivery_artifacts_episode FOREIGN KEY (episode_id) REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS validation_evidence (
    validation_id            VARCHAR(128) NOT NULL PRIMARY KEY,
    episode_id               VARCHAR(128) NOT NULL,
    delivery_id              VARCHAR(128) NOT NULL,
    validator_name            VARCHAR(255) NOT NULL,
    validator_version         VARCHAR(64) NOT NULL,
    valid                     BOOLEAN NOT NULL,
    reason_code               VARCHAR(128) NOT NULL,
    evidence_refs             JSON NULL,
    payload_hash              CHAR(71) NOT NULL,
    created_at                DATETIME(6) NOT NULL,
    UNIQUE KEY uk_validation_delivery (delivery_id, validator_name, validator_version),
    CONSTRAINT fk_validation_evidence_episode FOREIGN KEY (episode_id) REFERENCES commerce_episodes (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
