// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package blockchain_adapter

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/stablepay/blockchain-adapter/kitex_gen/stablepay/common"
)

type TxStatus int64

const (
	TxStatus_PENDING   TxStatus = 1
	TxStatus_CONFIRMED TxStatus = 2
	TxStatus_FAILED    TxStatus = 3
)

func (p TxStatus) String() string {
	switch p {
	case TxStatus_PENDING:
		return "PENDING"
	case TxStatus_CONFIRMED:
		return "CONFIRMED"
	case TxStatus_FAILED:
		return "FAILED"
	}
	return "<UNSET>"
}

func TxStatusFromString(s string) (TxStatus, error) {
	switch s {
	case "PENDING":
		return TxStatus_PENDING, nil
	case "CONFIRMED":
		return TxStatus_CONFIRMED, nil
	case "FAILED":
		return TxStatus_FAILED, nil
	}
	return TxStatus(0), fmt.Errorf("not a valid TxStatus string")
}

func TxStatusPtr(v TxStatus) *TxStatus { return &v }
func (p *TxStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TxStatus(result.Int64)
	return
}

func (p *TxStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TransferStableCoinRequest struct {
	Base              *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	FromWalletAddress *string         `thrift:"from_wallet_address,2,optional" frugal:"2,optional,string" json:"from_wallet_address,omitempty"`
	ToWalletAddress   string          `thrift:"to_wallet_address,3" frugal:"3,default,string" json:"to_wallet_address"`
	AmountMinor       int64           `thrift:"amount_minor,4" frugal:"4,default,i64" json:"amount_minor"`
	Currency          common.Currency `thrift:"currency,5" frugal:"5,default,Currency" json:"currency"`
	SignedTxBase64    *string         `thrift:"signed_tx_base64,6,optional" frugal:"6,optional,string" json:"signed_tx_base64,omitempty"`
}

func NewTransferStableCoinRequest() *TransferStableCoinRequest {
	return &TransferStableCoinRequest{}
}

func (p *TransferStableCoinRequest) InitDefault() {
}

var TransferStableCoinRequest_Base_DEFAULT *common.BaseReq

func (p *TransferStableCoinRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return TransferStableCoinRequest_Base_DEFAULT
	}
	return p.Base
}

var TransferStableCoinRequest_FromWalletAddress_DEFAULT string

func (p *TransferStableCoinRequest) GetFromWalletAddress() (v string) {
	if !p.IsSetFromWalletAddress() {
		return TransferStableCoinRequest_FromWalletAddress_DEFAULT
	}
	return *p.FromWalletAddress
}

func (p *TransferStableCoinRequest) GetToWalletAddress() (v string) {
	return p.ToWalletAddress
}

func (p *TransferStableCoinRequest) GetAmountMinor() (v int64) {
	return p.AmountMinor
}

func (p *TransferStableCoinRequest) GetCurrency() (v common.Currency) {
	return p.Currency
}

var TransferStableCoinRequest_SignedTxBase64_DEFAULT string

func (p *TransferStableCoinRequest) GetSignedTxBase64() (v string) {
	if !p.IsSetSignedTxBase64() {
		return TransferStableCoinRequest_SignedTxBase64_DEFAULT
	}
	return *p.SignedTxBase64
}
func (p *TransferStableCoinRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *TransferStableCoinRequest) SetFromWalletAddress(val *string) {
	p.FromWalletAddress = val
}
func (p *TransferStableCoinRequest) SetToWalletAddress(val string) {
	p.ToWalletAddress = val
}
func (p *TransferStableCoinRequest) SetAmountMinor(val int64) {
	p.AmountMinor = val
}
func (p *TransferStableCoinRequest) SetCurrency(val common.Currency) {
	p.Currency = val
}
func (p *TransferStableCoinRequest) SetSignedTxBase64(val *string) {
	p.SignedTxBase64 = val
}

func (p *TransferStableCoinRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *TransferStableCoinRequest) IsSetFromWalletAddress() bool {
	return p.FromWalletAddress != nil
}

func (p *TransferStableCoinRequest) IsSetSignedTxBase64() bool {
	return p.SignedTxBase64 != nil
}

func (p *TransferStableCoinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TransferStableCoinRequest(%+v)", *p)
}

var fieldIDToName_TransferStableCoinRequest = map[int16]string{
	1: "base",
	2: "from_wallet_address",
	3: "to_wallet_address",
	4: "amount_minor",
	5: "currency",
	6: "signed_tx_base64",
}

type TransferStableCoinResponse struct {
	Base        *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	TxHash      common.TxHash    `thrift:"tx_hash,2" frugal:"2,default,string" json:"tx_hash"`
	Status      TxStatus         `thrift:"status,3" frugal:"3,default,TxStatus" json:"status"`
	ConfirmedAt *string          `thrift:"confirmed_at,4,optional" frugal:"4,optional,string" json:"confirmed_at,omitempty"`
}

func NewTransferStableCoinResponse() *TransferStableCoinResponse {
	return &TransferStableCoinResponse{}
}

func (p *TransferStableCoinResponse) InitDefault() {
}

var TransferStableCoinResponse_Base_DEFAULT *common.BaseResp

func (p *TransferStableCoinResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return TransferStableCoinResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *TransferStableCoinResponse) GetTxHash() (v common.TxHash) {
	return p.TxHash
}

func (p *TransferStableCoinResponse) GetStatus() (v TxStatus) {
	return p.Status
}

var TransferStableCoinResponse_ConfirmedAt_DEFAULT string

func (p *TransferStableCoinResponse) GetConfirmedAt() (v string) {
	if !p.IsSetConfirmedAt() {
		return TransferStableCoinResponse_ConfirmedAt_DEFAULT
	}
	return *p.ConfirmedAt
}
func (p *TransferStableCoinResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *TransferStableCoinResponse) SetTxHash(val common.TxHash) {
	p.TxHash = val
}
func (p *TransferStableCoinResponse) SetStatus(val TxStatus) {
	p.Status = val
}
func (p *TransferStableCoinResponse) SetConfirmedAt(val *string) {
	p.ConfirmedAt = val
}

func (p *TransferStableCoinResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *TransferStableCoinResponse) IsSetConfirmedAt() bool {
	return p.ConfirmedAt != nil
}

func (p *TransferStableCoinResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TransferStableCoinResponse(%+v)", *p)
}

var fieldIDToName_TransferStableCoinResponse = map[int16]string{
	1: "base",
	2: "tx_hash",
	3: "status",
	4: "confirmed_at",
}

type GetBalanceRequest struct {
	Base          *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	WalletAddress string          `thrift:"wallet_address,2" frugal:"2,default,string" json:"wallet_address"`
	Currency      common.Currency `thrift:"currency,3" frugal:"3,default,Currency" json:"currency"`
}

func NewGetBalanceRequest() *GetBalanceRequest {
	return &GetBalanceRequest{}
}

func (p *GetBalanceRequest) InitDefault() {
}

var GetBalanceRequest_Base_DEFAULT *common.BaseReq

func (p *GetBalanceRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetBalanceRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetBalanceRequest) GetWalletAddress() (v string) {
	return p.WalletAddress
}

func (p *GetBalanceRequest) GetCurrency() (v common.Currency) {
	return p.Currency
}
func (p *GetBalanceRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetBalanceRequest) SetWalletAddress(val string) {
	p.WalletAddress = val
}
func (p *GetBalanceRequest) SetCurrency(val common.Currency) {
	p.Currency = val
}

func (p *GetBalanceRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetBalanceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBalanceRequest(%+v)", *p)
}

var fieldIDToName_GetBalanceRequest = map[int16]string{
	1: "base",
	2: "wallet_address",
	3: "currency",
}

type GetBalanceResponse struct {
	Base         *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	BalanceMinor int64            `thrift:"balance_minor,2" frugal:"2,default,i64" json:"balance_minor"`
	Currency     common.Currency  `thrift:"currency,3" frugal:"3,default,Currency" json:"currency"`
}

func NewGetBalanceResponse() *GetBalanceResponse {
	return &GetBalanceResponse{}
}

func (p *GetBalanceResponse) InitDefault() {
}

var GetBalanceResponse_Base_DEFAULT *common.BaseResp

func (p *GetBalanceResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetBalanceResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetBalanceResponse) GetBalanceMinor() (v int64) {
	return p.BalanceMinor
}

func (p *GetBalanceResponse) GetCurrency() (v common.Currency) {
	return p.Currency
}
func (p *GetBalanceResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetBalanceResponse) SetBalanceMinor(val int64) {
	p.BalanceMinor = val
}
func (p *GetBalanceResponse) SetCurrency(val common.Currency) {
	p.Currency = val
}

func (p *GetBalanceResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetBalanceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBalanceResponse(%+v)", *p)
}

var fieldIDToName_GetBalanceResponse = map[int16]string{
	1: "base",
	2: "balance_minor",
	3: "currency",
}

type GetTxStatusRequest struct {
	Base   *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	TxHash common.TxHash   `thrift:"tx_hash,2" frugal:"2,default,string" json:"tx_hash"`
}

func NewGetTxStatusRequest() *GetTxStatusRequest {
	return &GetTxStatusRequest{}
}

func (p *GetTxStatusRequest) InitDefault() {
}

var GetTxStatusRequest_Base_DEFAULT *common.BaseReq

func (p *GetTxStatusRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return GetTxStatusRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *GetTxStatusRequest) GetTxHash() (v common.TxHash) {
	return p.TxHash
}
func (p *GetTxStatusRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *GetTxStatusRequest) SetTxHash(val common.TxHash) {
	p.TxHash = val
}

func (p *GetTxStatusRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetTxStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTxStatusRequest(%+v)", *p)
}

var fieldIDToName_GetTxStatusRequest = map[int16]string{
	1: "base",
	2: "tx_hash",
}

type GetTxStatusResponse struct {
	Base          *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	Status        TxStatus         `thrift:"status,2" frugal:"2,default,TxStatus" json:"status"`
	ConfirmedAt   *string          `thrift:"confirmed_at,3,optional" frugal:"3,optional,string" json:"confirmed_at,omitempty"`
	FailedAt      *string          `thrift:"failed_at,4,optional" frugal:"4,optional,string" json:"failed_at,omitempty"`
	ReasonCode    *string          `thrift:"reason_code,5,optional" frugal:"5,optional,string" json:"reason_code,omitempty"`
	ReasonMessage *string          `thrift:"reason_message,6,optional" frugal:"6,optional,string" json:"reason_message,omitempty"`
}

func NewGetTxStatusResponse() *GetTxStatusResponse {
	return &GetTxStatusResponse{}
}

func (p *GetTxStatusResponse) InitDefault() {
}

var GetTxStatusResponse_Base_DEFAULT *common.BaseResp

func (p *GetTxStatusResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetTxStatusResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetTxStatusResponse) GetStatus() (v TxStatus) {
	return p.Status
}

var GetTxStatusResponse_ConfirmedAt_DEFAULT string

func (p *GetTxStatusResponse) GetConfirmedAt() (v string) {
	if !p.IsSetConfirmedAt() {
		return GetTxStatusResponse_ConfirmedAt_DEFAULT
	}
	return *p.ConfirmedAt
}

var GetTxStatusResponse_FailedAt_DEFAULT string

func (p *GetTxStatusResponse) GetFailedAt() (v string) {
	if !p.IsSetFailedAt() {
		return GetTxStatusResponse_FailedAt_DEFAULT
	}
	return *p.FailedAt
}

var GetTxStatusResponse_ReasonCode_DEFAULT string

func (p *GetTxStatusResponse) GetReasonCode() (v string) {
	if !p.IsSetReasonCode() {
		return GetTxStatusResponse_ReasonCode_DEFAULT
	}
	return *p.ReasonCode
}

var GetTxStatusResponse_ReasonMessage_DEFAULT string

func (p *GetTxStatusResponse) GetReasonMessage() (v string) {
	if !p.IsSetReasonMessage() {
		return GetTxStatusResponse_ReasonMessage_DEFAULT
	}
	return *p.ReasonMessage
}
func (p *GetTxStatusResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetTxStatusResponse) SetStatus(val TxStatus) {
	p.Status = val
}
func (p *GetTxStatusResponse) SetConfirmedAt(val *string) {
	p.ConfirmedAt = val
}
func (p *GetTxStatusResponse) SetFailedAt(val *string) {
	p.FailedAt = val
}
func (p *GetTxStatusResponse) SetReasonCode(val *string) {
	p.ReasonCode = val
}
func (p *GetTxStatusResponse) SetReasonMessage(val *string) {
	p.ReasonMessage = val
}

func (p *GetTxStatusResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetTxStatusResponse) IsSetConfirmedAt() bool {
	return p.ConfirmedAt != nil
}

func (p *GetTxStatusResponse) IsSetFailedAt() bool {
	return p.FailedAt != nil
}

func (p *GetTxStatusResponse) IsSetReasonCode() bool {
	return p.ReasonCode != nil
}

func (p *GetTxStatusResponse) IsSetReasonMessage() bool {
	return p.ReasonMessage != nil
}

func (p *GetTxStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTxStatusResponse(%+v)", *p)
}

var fieldIDToName_GetTxStatusResponse = map[int16]string{
	1: "base",
	2: "status",
	3: "confirmed_at",
	4: "failed_at",
	5: "reason_code",
	6: "reason_message",
}

type BuildUnsignedTransactionRequest struct {
	Base              *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	FromWalletAddress string          `thrift:"from_wallet_address,2" frugal:"2,default,string" json:"from_wallet_address"`
	ToWalletAddress   string          `thrift:"to_wallet_address,3" frugal:"3,default,string" json:"to_wallet_address"`
	AmountMinor       int64           `thrift:"amount_minor,4" frugal:"4,default,i64" json:"amount_minor"`
	Currency          common.Currency `thrift:"currency,5" frugal:"5,default,Currency" json:"currency"`
	TxId              *string         `thrift:"tx_id,6,optional" frugal:"6,optional,string" json:"tx_id,omitempty"`
}

func NewBuildUnsignedTransactionRequest() *BuildUnsignedTransactionRequest {
	return &BuildUnsignedTransactionRequest{}
}

func (p *BuildUnsignedTransactionRequest) InitDefault() {
}

var BuildUnsignedTransactionRequest_Base_DEFAULT *common.BaseReq

func (p *BuildUnsignedTransactionRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return BuildUnsignedTransactionRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *BuildUnsignedTransactionRequest) GetFromWalletAddress() (v string) {
	return p.FromWalletAddress
}

func (p *BuildUnsignedTransactionRequest) GetToWalletAddress() (v string) {
	return p.ToWalletAddress
}

func (p *BuildUnsignedTransactionRequest) GetAmountMinor() (v int64) {
	return p.AmountMinor
}

func (p *BuildUnsignedTransactionRequest) GetCurrency() (v common.Currency) {
	return p.Currency
}

var BuildUnsignedTransactionRequest_TxId_DEFAULT string

func (p *BuildUnsignedTransactionRequest) GetTxId() (v string) {
	if !p.IsSetTxId() {
		return BuildUnsignedTransactionRequest_TxId_DEFAULT
	}
	return *p.TxId
}
func (p *BuildUnsignedTransactionRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *BuildUnsignedTransactionRequest) SetFromWalletAddress(val string) {
	p.FromWalletAddress = val
}
func (p *BuildUnsignedTransactionRequest) SetToWalletAddress(val string) {
	p.ToWalletAddress = val
}
func (p *BuildUnsignedTransactionRequest) SetAmountMinor(val int64) {
	p.AmountMinor = val
}
func (p *BuildUnsignedTransactionRequest) SetCurrency(val common.Currency) {
	p.Currency = val
}
func (p *BuildUnsignedTransactionRequest) SetTxId(val *string) {
	p.TxId = val
}

func (p *BuildUnsignedTransactionRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *BuildUnsignedTransactionRequest) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *BuildUnsignedTransactionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BuildUnsignedTransactionRequest(%+v)", *p)
}

var fieldIDToName_BuildUnsignedTransactionRequest = map[int16]string{
	1: "base",
	2: "from_wallet_address",
	3: "to_wallet_address",
	4: "amount_minor",
	5: "currency",
	6: "tx_id",
}

type BuildUnsignedTransactionResponse struct {
	Base             *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	UnsignedTxBase64 string           `thrift:"unsigned_tx_base64,2" frugal:"2,default,string" json:"unsigned_tx_base64"`
	RecentBlockhash  string           `thrift:"recent_blockhash,3" frugal:"3,default,string" json:"recent_blockhash"`
	FeeEstimateMinor int64            `thrift:"fee_estimate_minor,4" frugal:"4,default,i64" json:"fee_estimate_minor"`
}

func NewBuildUnsignedTransactionResponse() *BuildUnsignedTransactionResponse {
	return &BuildUnsignedTransactionResponse{}
}

func (p *BuildUnsignedTransactionResponse) InitDefault() {
}

var BuildUnsignedTransactionResponse_Base_DEFAULT *common.BaseResp

func (p *BuildUnsignedTransactionResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return BuildUnsignedTransactionResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *BuildUnsignedTransactionResponse) GetUnsignedTxBase64() (v string) {
	return p.UnsignedTxBase64
}

func (p *BuildUnsignedTransactionResponse) GetRecentBlockhash() (v string) {
	return p.RecentBlockhash
}

func (p *BuildUnsignedTransactionResponse) GetFeeEstimateMinor() (v int64) {
	return p.FeeEstimateMinor
}
func (p *BuildUnsignedTransactionResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *BuildUnsignedTransactionResponse) SetUnsignedTxBase64(val string) {
	p.UnsignedTxBase64 = val
}
func (p *BuildUnsignedTransactionResponse) SetRecentBlockhash(val string) {
	p.RecentBlockhash = val
}
func (p *BuildUnsignedTransactionResponse) SetFeeEstimateMinor(val int64) {
	p.FeeEstimateMinor = val
}

func (p *BuildUnsignedTransactionResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BuildUnsignedTransactionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BuildUnsignedTransactionResponse(%+v)", *p)
}

var fieldIDToName_BuildUnsignedTransactionResponse = map[int16]string{
	1: "base",
	2: "unsigned_tx_base64",
	3: "recent_blockhash",
	4: "fee_estimate_minor",
}

type SubmitSignedTransactionRequest struct {
	Base           *common.BaseReq `thrift:"base,1" frugal:"1,default,common.BaseReq" json:"base"`
	SignedTxBase64 string          `thrift:"signed_tx_base64,2" frugal:"2,default,string" json:"signed_tx_base64"`
	TxId           *string         `thrift:"tx_id,3,optional" frugal:"3,optional,string" json:"tx_id,omitempty"`
}

func NewSubmitSignedTransactionRequest() *SubmitSignedTransactionRequest {
	return &SubmitSignedTransactionRequest{}
}

func (p *SubmitSignedTransactionRequest) InitDefault() {
}

var SubmitSignedTransactionRequest_Base_DEFAULT *common.BaseReq

func (p *SubmitSignedTransactionRequest) GetBase() (v *common.BaseReq) {
	if !p.IsSetBase() {
		return SubmitSignedTransactionRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *SubmitSignedTransactionRequest) GetSignedTxBase64() (v string) {
	return p.SignedTxBase64
}

var SubmitSignedTransactionRequest_TxId_DEFAULT string

func (p *SubmitSignedTransactionRequest) GetTxId() (v string) {
	if !p.IsSetTxId() {
		return SubmitSignedTransactionRequest_TxId_DEFAULT
	}
	return *p.TxId
}
func (p *SubmitSignedTransactionRequest) SetBase(val *common.BaseReq) {
	p.Base = val
}
func (p *SubmitSignedTransactionRequest) SetSignedTxBase64(val string) {
	p.SignedTxBase64 = val
}
func (p *SubmitSignedTransactionRequest) SetTxId(val *string) {
	p.TxId = val
}

func (p *SubmitSignedTransactionRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *SubmitSignedTransactionRequest) IsSetTxId() bool {
	return p.TxId != nil
}

func (p *SubmitSignedTransactionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitSignedTransactionRequest(%+v)", *p)
}

var fieldIDToName_SubmitSignedTransactionRequest = map[int16]string{
	1: "base",
	2: "signed_tx_base64",
	3: "tx_id",
}

type SubmitSignedTransactionResponse struct {
	Base   *common.BaseResp `thrift:"base,1" frugal:"1,default,common.BaseResp" json:"base"`
	TxHash common.TxHash    `thrift:"tx_hash,2" frugal:"2,default,string" json:"tx_hash"`
	Status TxStatus         `thrift:"status,3" frugal:"3,default,TxStatus" json:"status"`
}

func NewSubmitSignedTransactionResponse() *SubmitSignedTransactionResponse {
	return &SubmitSignedTransactionResponse{}
}

func (p *SubmitSignedTransactionResponse) InitDefault() {
}

var SubmitSignedTransactionResponse_Base_DEFAULT *common.BaseResp

func (p *SubmitSignedTransactionResponse) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return SubmitSignedTransactionResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *SubmitSignedTransactionResponse) GetTxHash() (v common.TxHash) {
	return p.TxHash
}

func (p *SubmitSignedTransactionResponse) GetStatus() (v TxStatus) {
	return p.Status
}
func (p *SubmitSignedTransactionResponse) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *SubmitSignedTransactionResponse) SetTxHash(val common.TxHash) {
	p.TxHash = val
}
func (p *SubmitSignedTransactionResponse) SetStatus(val TxStatus) {
	p.Status = val
}

func (p *SubmitSignedTransactionResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *SubmitSignedTransactionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitSignedTransactionResponse(%+v)", *p)
}

var fieldIDToName_SubmitSignedTransactionResponse = map[int16]string{
	1: "base",
	2: "tx_hash",
	3: "status",
}

type BlockchainAdapterService interface {
	TransferStableCoin(ctx context.Context, req *TransferStableCoinRequest) (r *TransferStableCoinResponse, err error)

	GetBalance(ctx context.Context, req *GetBalanceRequest) (r *GetBalanceResponse, err error)

	GetTxStatus(ctx context.Context, req *GetTxStatusRequest) (r *GetTxStatusResponse, err error)

	BuildUnsignedTransaction(ctx context.Context, req *BuildUnsignedTransactionRequest) (r *BuildUnsignedTransactionResponse, err error)

	SubmitSignedTransaction(ctx context.Context, req *SubmitSignedTransactionRequest) (r *SubmitSignedTransactionResponse, err error)
}

type BlockchainAdapterServiceTransferStableCoinArgs struct {
	Req *TransferStableCoinRequest `thrift:"req,1" frugal:"1,default,TransferStableCoinRequest" json:"req"`
}

func NewBlockchainAdapterServiceTransferStableCoinArgs() *BlockchainAdapterServiceTransferStableCoinArgs {
	return &BlockchainAdapterServiceTransferStableCoinArgs{}
}

func (p *BlockchainAdapterServiceTransferStableCoinArgs) InitDefault() {
}

var BlockchainAdapterServiceTransferStableCoinArgs_Req_DEFAULT *TransferStableCoinRequest

func (p *BlockchainAdapterServiceTransferStableCoinArgs) GetReq() (v *TransferStableCoinRequest) {
	if !p.IsSetReq() {
		return BlockchainAdapterServiceTransferStableCoinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BlockchainAdapterServiceTransferStableCoinArgs) SetReq(val *TransferStableCoinRequest) {
	p.Req = val
}

func (p *BlockchainAdapterServiceTransferStableCoinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BlockchainAdapterServiceTransferStableCoinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceTransferStableCoinArgs(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceTransferStableCoinArgs = map[int16]string{
	1: "req",
}

type BlockchainAdapterServiceTransferStableCoinResult struct {
	Success *TransferStableCoinResponse `thrift:"success,0,optional" frugal:"0,optional,TransferStableCoinResponse" json:"success,omitempty"`
}

func NewBlockchainAdapterServiceTransferStableCoinResult() *BlockchainAdapterServiceTransferStableCoinResult {
	return &BlockchainAdapterServiceTransferStableCoinResult{}
}

func (p *BlockchainAdapterServiceTransferStableCoinResult) InitDefault() {
}

var BlockchainAdapterServiceTransferStableCoinResult_Success_DEFAULT *TransferStableCoinResponse

func (p *BlockchainAdapterServiceTransferStableCoinResult) GetSuccess() (v *TransferStableCoinResponse) {
	if !p.IsSetSuccess() {
		return BlockchainAdapterServiceTransferStableCoinResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BlockchainAdapterServiceTransferStableCoinResult) SetSuccess(x interface{}) {
	p.Success = x.(*TransferStableCoinResponse)
}

func (p *BlockchainAdapterServiceTransferStableCoinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BlockchainAdapterServiceTransferStableCoinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceTransferStableCoinResult(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceTransferStableCoinResult = map[int16]string{
	0: "success",
}

type BlockchainAdapterServiceGetBalanceArgs struct {
	Req *GetBalanceRequest `thrift:"req,1" frugal:"1,default,GetBalanceRequest" json:"req"`
}

func NewBlockchainAdapterServiceGetBalanceArgs() *BlockchainAdapterServiceGetBalanceArgs {
	return &BlockchainAdapterServiceGetBalanceArgs{}
}

func (p *BlockchainAdapterServiceGetBalanceArgs) InitDefault() {
}

var BlockchainAdapterServiceGetBalanceArgs_Req_DEFAULT *GetBalanceRequest

func (p *BlockchainAdapterServiceGetBalanceArgs) GetReq() (v *GetBalanceRequest) {
	if !p.IsSetReq() {
		return BlockchainAdapterServiceGetBalanceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BlockchainAdapterServiceGetBalanceArgs) SetReq(val *GetBalanceRequest) {
	p.Req = val
}

func (p *BlockchainAdapterServiceGetBalanceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BlockchainAdapterServiceGetBalanceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceGetBalanceArgs(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceGetBalanceArgs = map[int16]string{
	1: "req",
}

type BlockchainAdapterServiceGetBalanceResult struct {
	Success *GetBalanceResponse `thrift:"success,0,optional" frugal:"0,optional,GetBalanceResponse" json:"success,omitempty"`
}

func NewBlockchainAdapterServiceGetBalanceResult() *BlockchainAdapterServiceGetBalanceResult {
	return &BlockchainAdapterServiceGetBalanceResult{}
}

func (p *BlockchainAdapterServiceGetBalanceResult) InitDefault() {
}

var BlockchainAdapterServiceGetBalanceResult_Success_DEFAULT *GetBalanceResponse

func (p *BlockchainAdapterServiceGetBalanceResult) GetSuccess() (v *GetBalanceResponse) {
	if !p.IsSetSuccess() {
		return BlockchainAdapterServiceGetBalanceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BlockchainAdapterServiceGetBalanceResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetBalanceResponse)
}

func (p *BlockchainAdapterServiceGetBalanceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BlockchainAdapterServiceGetBalanceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceGetBalanceResult(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceGetBalanceResult = map[int16]string{
	0: "success",
}

type BlockchainAdapterServiceGetTxStatusArgs struct {
	Req *GetTxStatusRequest `thrift:"req,1" frugal:"1,default,GetTxStatusRequest" json:"req"`
}

func NewBlockchainAdapterServiceGetTxStatusArgs() *BlockchainAdapterServiceGetTxStatusArgs {
	return &BlockchainAdapterServiceGetTxStatusArgs{}
}

func (p *BlockchainAdapterServiceGetTxStatusArgs) InitDefault() {
}

var BlockchainAdapterServiceGetTxStatusArgs_Req_DEFAULT *GetTxStatusRequest

func (p *BlockchainAdapterServiceGetTxStatusArgs) GetReq() (v *GetTxStatusRequest) {
	if !p.IsSetReq() {
		return BlockchainAdapterServiceGetTxStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BlockchainAdapterServiceGetTxStatusArgs) SetReq(val *GetTxStatusRequest) {
	p.Req = val
}

func (p *BlockchainAdapterServiceGetTxStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BlockchainAdapterServiceGetTxStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceGetTxStatusArgs(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceGetTxStatusArgs = map[int16]string{
	1: "req",
}

type BlockchainAdapterServiceGetTxStatusResult struct {
	Success *GetTxStatusResponse `thrift:"success,0,optional" frugal:"0,optional,GetTxStatusResponse" json:"success,omitempty"`
}

func NewBlockchainAdapterServiceGetTxStatusResult() *BlockchainAdapterServiceGetTxStatusResult {
	return &BlockchainAdapterServiceGetTxStatusResult{}
}

func (p *BlockchainAdapterServiceGetTxStatusResult) InitDefault() {
}

var BlockchainAdapterServiceGetTxStatusResult_Success_DEFAULT *GetTxStatusResponse

func (p *BlockchainAdapterServiceGetTxStatusResult) GetSuccess() (v *GetTxStatusResponse) {
	if !p.IsSetSuccess() {
		return BlockchainAdapterServiceGetTxStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BlockchainAdapterServiceGetTxStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTxStatusResponse)
}

func (p *BlockchainAdapterServiceGetTxStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BlockchainAdapterServiceGetTxStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceGetTxStatusResult(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceGetTxStatusResult = map[int16]string{
	0: "success",
}

type BlockchainAdapterServiceBuildUnsignedTransactionArgs struct {
	Req *BuildUnsignedTransactionRequest `thrift:"req,1" frugal:"1,default,BuildUnsignedTransactionRequest" json:"req"`
}

func NewBlockchainAdapterServiceBuildUnsignedTransactionArgs() *BlockchainAdapterServiceBuildUnsignedTransactionArgs {
	return &BlockchainAdapterServiceBuildUnsignedTransactionArgs{}
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionArgs) InitDefault() {
}

var BlockchainAdapterServiceBuildUnsignedTransactionArgs_Req_DEFAULT *BuildUnsignedTransactionRequest

func (p *BlockchainAdapterServiceBuildUnsignedTransactionArgs) GetReq() (v *BuildUnsignedTransactionRequest) {
	if !p.IsSetReq() {
		return BlockchainAdapterServiceBuildUnsignedTransactionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BlockchainAdapterServiceBuildUnsignedTransactionArgs) SetReq(val *BuildUnsignedTransactionRequest) {
	p.Req = val
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceBuildUnsignedTransactionArgs(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceBuildUnsignedTransactionArgs = map[int16]string{
	1: "req",
}

type BlockchainAdapterServiceBuildUnsignedTransactionResult struct {
	Success *BuildUnsignedTransactionResponse `thrift:"success,0,optional" frugal:"0,optional,BuildUnsignedTransactionResponse" json:"success,omitempty"`
}

func NewBlockchainAdapterServiceBuildUnsignedTransactionResult() *BlockchainAdapterServiceBuildUnsignedTransactionResult {
	return &BlockchainAdapterServiceBuildUnsignedTransactionResult{}
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionResult) InitDefault() {
}

var BlockchainAdapterServiceBuildUnsignedTransactionResult_Success_DEFAULT *BuildUnsignedTransactionResponse

func (p *BlockchainAdapterServiceBuildUnsignedTransactionResult) GetSuccess() (v *BuildUnsignedTransactionResponse) {
	if !p.IsSetSuccess() {
		return BlockchainAdapterServiceBuildUnsignedTransactionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BlockchainAdapterServiceBuildUnsignedTransactionResult) SetSuccess(x interface{}) {
	p.Success = x.(*BuildUnsignedTransactionResponse)
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BlockchainAdapterServiceBuildUnsignedTransactionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceBuildUnsignedTransactionResult(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceBuildUnsignedTransactionResult = map[int16]string{
	0: "success",
}

type BlockchainAdapterServiceSubmitSignedTransactionArgs struct {
	Req *SubmitSignedTransactionRequest `thrift:"req,1" frugal:"1,default,SubmitSignedTransactionRequest" json:"req"`
}

func NewBlockchainAdapterServiceSubmitSignedTransactionArgs() *BlockchainAdapterServiceSubmitSignedTransactionArgs {
	return &BlockchainAdapterServiceSubmitSignedTransactionArgs{}
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionArgs) InitDefault() {
}

var BlockchainAdapterServiceSubmitSignedTransactionArgs_Req_DEFAULT *SubmitSignedTransactionRequest

func (p *BlockchainAdapterServiceSubmitSignedTransactionArgs) GetReq() (v *SubmitSignedTransactionRequest) {
	if !p.IsSetReq() {
		return BlockchainAdapterServiceSubmitSignedTransactionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BlockchainAdapterServiceSubmitSignedTransactionArgs) SetReq(val *SubmitSignedTransactionRequest) {
	p.Req = val
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceSubmitSignedTransactionArgs(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceSubmitSignedTransactionArgs = map[int16]string{
	1: "req",
}

type BlockchainAdapterServiceSubmitSignedTransactionResult struct {
	Success *SubmitSignedTransactionResponse `thrift:"success,0,optional" frugal:"0,optional,SubmitSignedTransactionResponse" json:"success,omitempty"`
}

func NewBlockchainAdapterServiceSubmitSignedTransactionResult() *BlockchainAdapterServiceSubmitSignedTransactionResult {
	return &BlockchainAdapterServiceSubmitSignedTransactionResult{}
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionResult) InitDefault() {
}

var BlockchainAdapterServiceSubmitSignedTransactionResult_Success_DEFAULT *SubmitSignedTransactionResponse

func (p *BlockchainAdapterServiceSubmitSignedTransactionResult) GetSuccess() (v *SubmitSignedTransactionResponse) {
	if !p.IsSetSuccess() {
		return BlockchainAdapterServiceSubmitSignedTransactionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BlockchainAdapterServiceSubmitSignedTransactionResult) SetSuccess(x interface{}) {
	p.Success = x.(*SubmitSignedTransactionResponse)
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BlockchainAdapterServiceSubmitSignedTransactionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockchainAdapterServiceSubmitSignedTransactionResult(%+v)", *p)
}

var fieldIDToName_BlockchainAdapterServiceSubmitSignedTransactionResult = map[int16]string{
	0: "success",
}
