// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ErrorCode int64

const (
	ErrorCode_SUCCESS                       ErrorCode = 0
	ErrorCode_INVALID_PARAMETERS            ErrorCode = 10001
	ErrorCode_RESOURCE_NOT_FOUND            ErrorCode = 10002
	ErrorCode_PERMISSION_DENIED             ErrorCode = 10003
	ErrorCode_SIGNATURE_VERIFICATION_FAILED ErrorCode = 10004
	ErrorCode_INSUFFICIENT_BALANCE          ErrorCode = 20001
	ErrorCode_PAYMENT_ALREADY_EXISTS        ErrorCode = 20002
	ErrorCode_BLOCKCHAIN_NETWORK_ERROR      ErrorCode = 20003
	ErrorCode_GAS_SUBSIDY_FAILED            ErrorCode = 20004
	ErrorCode_INTERNAL_SERVER_ERROR         ErrorCode = 30001
	ErrorCode_SERVICE_UNAVAILABLE           ErrorCode = 30002
	ErrorCode_DATABASE_CONNECTION_ERROR     ErrorCode = 30003
	ErrorCode_RATE_LIMIT_EXCEEDED           ErrorCode = 30004
	ErrorCode_TWEET_NOT_FOUND               ErrorCode = 40001
	ErrorCode_TWEET_NOT_VERIFIED            ErrorCode = 40002
	ErrorCode_WALLET_NOT_FOUND_IN_TWEET     ErrorCode = 40003
	ErrorCode_VERIFICATION_ALREADY_CLAIMED  ErrorCode = 40004
	ErrorCode_INVALID_TWEET_URL             ErrorCode = 40005
)

func (p ErrorCode) String() string {
	switch p {
	case ErrorCode_SUCCESS:
		return "SUCCESS"
	case ErrorCode_INVALID_PARAMETERS:
		return "INVALID_PARAMETERS"
	case ErrorCode_RESOURCE_NOT_FOUND:
		return "RESOURCE_NOT_FOUND"
	case ErrorCode_PERMISSION_DENIED:
		return "PERMISSION_DENIED"
	case ErrorCode_SIGNATURE_VERIFICATION_FAILED:
		return "SIGNATURE_VERIFICATION_FAILED"
	case ErrorCode_INSUFFICIENT_BALANCE:
		return "INSUFFICIENT_BALANCE"
	case ErrorCode_PAYMENT_ALREADY_EXISTS:
		return "PAYMENT_ALREADY_EXISTS"
	case ErrorCode_BLOCKCHAIN_NETWORK_ERROR:
		return "BLOCKCHAIN_NETWORK_ERROR"
	case ErrorCode_GAS_SUBSIDY_FAILED:
		return "GAS_SUBSIDY_FAILED"
	case ErrorCode_INTERNAL_SERVER_ERROR:
		return "INTERNAL_SERVER_ERROR"
	case ErrorCode_SERVICE_UNAVAILABLE:
		return "SERVICE_UNAVAILABLE"
	case ErrorCode_DATABASE_CONNECTION_ERROR:
		return "DATABASE_CONNECTION_ERROR"
	case ErrorCode_RATE_LIMIT_EXCEEDED:
		return "RATE_LIMIT_EXCEEDED"
	case ErrorCode_TWEET_NOT_FOUND:
		return "TWEET_NOT_FOUND"
	case ErrorCode_TWEET_NOT_VERIFIED:
		return "TWEET_NOT_VERIFIED"
	case ErrorCode_WALLET_NOT_FOUND_IN_TWEET:
		return "WALLET_NOT_FOUND_IN_TWEET"
	case ErrorCode_VERIFICATION_ALREADY_CLAIMED:
		return "VERIFICATION_ALREADY_CLAIMED"
	case ErrorCode_INVALID_TWEET_URL:
		return "INVALID_TWEET_URL"
	}
	return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "SUCCESS":
		return ErrorCode_SUCCESS, nil
	case "INVALID_PARAMETERS":
		return ErrorCode_INVALID_PARAMETERS, nil
	case "RESOURCE_NOT_FOUND":
		return ErrorCode_RESOURCE_NOT_FOUND, nil
	case "PERMISSION_DENIED":
		return ErrorCode_PERMISSION_DENIED, nil
	case "SIGNATURE_VERIFICATION_FAILED":
		return ErrorCode_SIGNATURE_VERIFICATION_FAILED, nil
	case "INSUFFICIENT_BALANCE":
		return ErrorCode_INSUFFICIENT_BALANCE, nil
	case "PAYMENT_ALREADY_EXISTS":
		return ErrorCode_PAYMENT_ALREADY_EXISTS, nil
	case "BLOCKCHAIN_NETWORK_ERROR":
		return ErrorCode_BLOCKCHAIN_NETWORK_ERROR, nil
	case "GAS_SUBSIDY_FAILED":
		return ErrorCode_GAS_SUBSIDY_FAILED, nil
	case "INTERNAL_SERVER_ERROR":
		return ErrorCode_INTERNAL_SERVER_ERROR, nil
	case "SERVICE_UNAVAILABLE":
		return ErrorCode_SERVICE_UNAVAILABLE, nil
	case "DATABASE_CONNECTION_ERROR":
		return ErrorCode_DATABASE_CONNECTION_ERROR, nil
	case "RATE_LIMIT_EXCEEDED":
		return ErrorCode_RATE_LIMIT_EXCEEDED, nil
	case "TWEET_NOT_FOUND":
		return ErrorCode_TWEET_NOT_FOUND, nil
	case "TWEET_NOT_VERIFIED":
		return ErrorCode_TWEET_NOT_VERIFIED, nil
	case "WALLET_NOT_FOUND_IN_TWEET":
		return ErrorCode_WALLET_NOT_FOUND_IN_TWEET, nil
	case "VERIFICATION_ALREADY_CLAIMED":
		return ErrorCode_VERIFICATION_ALREADY_CLAIMED, nil
	case "INVALID_TWEET_URL":
		return ErrorCode_INVALID_TWEET_URL, nil
	}
	return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}

func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }
func (p *ErrorCode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ErrorCode(result.Int64)
	return
}

func (p *ErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Currency int64

const (
	Currency_USDC Currency = 1
	Currency_USDT Currency = 2
)

func (p Currency) String() string {
	switch p {
	case Currency_USDC:
		return "USDC"
	case Currency_USDT:
		return "USDT"
	}
	return "<UNSET>"
}

func CurrencyFromString(s string) (Currency, error) {
	switch s {
	case "USDC":
		return Currency_USDC, nil
	case "USDT":
		return Currency_USDT, nil
	}
	return Currency(0), fmt.Errorf("not a valid Currency string")
}

func CurrencyPtr(v Currency) *Currency { return &v }
func (p *Currency) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Currency(result.Int64)
	return
}

func (p *Currency) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type PaymentStatus int64

const (
	PaymentStatus_PENDING   PaymentStatus = 1
	PaymentStatus_CONFIRMED PaymentStatus = 2
	PaymentStatus_FAILED    PaymentStatus = 3
)

func (p PaymentStatus) String() string {
	switch p {
	case PaymentStatus_PENDING:
		return "PENDING"
	case PaymentStatus_CONFIRMED:
		return "CONFIRMED"
	case PaymentStatus_FAILED:
		return "FAILED"
	}
	return "<UNSET>"
}

func PaymentStatusFromString(s string) (PaymentStatus, error) {
	switch s {
	case "PENDING":
		return PaymentStatus_PENDING, nil
	case "CONFIRMED":
		return PaymentStatus_CONFIRMED, nil
	case "FAILED":
		return PaymentStatus_FAILED, nil
	}
	return PaymentStatus(0), fmt.Errorf("not a valid PaymentStatus string")
}

func PaymentStatusPtr(v PaymentStatus) *PaymentStatus { return &v }
func (p *PaymentStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PaymentStatus(result.Int64)
	return
}

func (p *PaymentStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type DID = string

type TxId = string

type TxHash = string

type BaseReq struct {
	RequestId      *string `thrift:"request_id,1,optional" frugal:"1,optional,string" json:"request_id,omitempty"`
	TraceId        *string `thrift:"trace_id,2,optional" frugal:"2,optional,string" json:"trace_id,omitempty"`
	TimestampMs    *int64  `thrift:"timestamp_ms,3,optional" frugal:"3,optional,i64" json:"timestamp_ms,omitempty"`
	IdempotencyKey *string `thrift:"idempotency_key,4,optional" frugal:"4,optional,string" json:"idempotency_key,omitempty"`
}

func NewBaseReq() *BaseReq {
	return &BaseReq{}
}

func (p *BaseReq) InitDefault() {
}

var BaseReq_RequestId_DEFAULT string

func (p *BaseReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return BaseReq_RequestId_DEFAULT
	}
	return *p.RequestId
}

var BaseReq_TraceId_DEFAULT string

func (p *BaseReq) GetTraceId() (v string) {
	if !p.IsSetTraceId() {
		return BaseReq_TraceId_DEFAULT
	}
	return *p.TraceId
}

var BaseReq_TimestampMs_DEFAULT int64

func (p *BaseReq) GetTimestampMs() (v int64) {
	if !p.IsSetTimestampMs() {
		return BaseReq_TimestampMs_DEFAULT
	}
	return *p.TimestampMs
}

var BaseReq_IdempotencyKey_DEFAULT string

func (p *BaseReq) GetIdempotencyKey() (v string) {
	if !p.IsSetIdempotencyKey() {
		return BaseReq_IdempotencyKey_DEFAULT
	}
	return *p.IdempotencyKey
}
func (p *BaseReq) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *BaseReq) SetTraceId(val *string) {
	p.TraceId = val
}
func (p *BaseReq) SetTimestampMs(val *int64) {
	p.TimestampMs = val
}
func (p *BaseReq) SetIdempotencyKey(val *string) {
	p.IdempotencyKey = val
}

func (p *BaseReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *BaseReq) IsSetTraceId() bool {
	return p.TraceId != nil
}

func (p *BaseReq) IsSetTimestampMs() bool {
	return p.TimestampMs != nil
}

func (p *BaseReq) IsSetIdempotencyKey() bool {
	return p.IdempotencyKey != nil
}

func (p *BaseReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseReq(%+v)", *p)
}

var fieldIDToName_BaseReq = map[int16]string{
	1: "request_id",
	2: "trace_id",
	3: "timestamp_ms",
	4: "idempotency_key",
}

type BaseResp struct {
	Code      int32   `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message   string  `thrift:"message,2" frugal:"2,default,string" json:"message"`
	RequestId *string `thrift:"request_id,3,optional" frugal:"3,optional,string" json:"request_id,omitempty"`
	TraceId   *string `thrift:"trace_id,4,optional" frugal:"4,optional,string" json:"trace_id,omitempty"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMessage() (v string) {
	return p.Message
}

var BaseResp_RequestId_DEFAULT string

func (p *BaseResp) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return BaseResp_RequestId_DEFAULT
	}
	return *p.RequestId
}

var BaseResp_TraceId_DEFAULT string

func (p *BaseResp) GetTraceId() (v string) {
	if !p.IsSetTraceId() {
		return BaseResp_TraceId_DEFAULT
	}
	return *p.TraceId
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMessage(val string) {
	p.Message = val
}
func (p *BaseResp) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *BaseResp) SetTraceId(val *string) {
	p.TraceId = val
}

func (p *BaseResp) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *BaseResp) IsSetTraceId() bool {
	return p.TraceId != nil
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "message",
	3: "request_id",
	4: "trace_id",
}

type PageRequest struct {
	Limit  int32 `thrift:"limit,1" frugal:"1,default,i32" json:"limit"`
	Offset int32 `thrift:"offset,2" frugal:"2,default,i32" json:"offset"`
}

func NewPageRequest() *PageRequest {
	return &PageRequest{}
}

func (p *PageRequest) InitDefault() {
}

func (p *PageRequest) GetLimit() (v int32) {
	return p.Limit
}

func (p *PageRequest) GetOffset() (v int32) {
	return p.Offset
}
func (p *PageRequest) SetLimit(val int32) {
	p.Limit = val
}
func (p *PageRequest) SetOffset(val int32) {
	p.Offset = val
}

func (p *PageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequest(%+v)", *p)
}

var fieldIDToName_PageRequest = map[int16]string{
	1: "limit",
	2: "offset",
}

type PageResult_ struct {
	Total int32 `thrift:"total,1" frugal:"1,default,i32" json:"total"`
}

func NewPageResult_() *PageResult_ {
	return &PageResult_{}
}

func (p *PageResult_) InitDefault() {
}

func (p *PageResult_) GetTotal() (v int32) {
	return p.Total
}
func (p *PageResult_) SetTotal(val int32) {
	p.Total = val
}

func (p *PageResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResult_(%+v)", *p)
}

var fieldIDToName_PageResult_ = map[int16]string{
	1: "total",
}

type MoneyMinor struct {
	AmountMinor int64    `thrift:"amount_minor,1" frugal:"1,default,i64" json:"amount_minor"`
	Currency    Currency `thrift:"currency,2" frugal:"2,default,Currency" json:"currency"`
}

func NewMoneyMinor() *MoneyMinor {
	return &MoneyMinor{}
}

func (p *MoneyMinor) InitDefault() {
}

func (p *MoneyMinor) GetAmountMinor() (v int64) {
	return p.AmountMinor
}

func (p *MoneyMinor) GetCurrency() (v Currency) {
	return p.Currency
}
func (p *MoneyMinor) SetAmountMinor(val int64) {
	p.AmountMinor = val
}
func (p *MoneyMinor) SetCurrency(val Currency) {
	p.Currency = val
}

func (p *MoneyMinor) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MoneyMinor(%+v)", *p)
}

var fieldIDToName_MoneyMinor = map[int16]string{
	1: "amount_minor",
	2: "currency",
}
