apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: stablepay-dev
spec:
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: stablepay-dev
spec:
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 8Gi
