apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-did-service
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-payment-service
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-blockchain-adapter
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-verification-service
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-query-service
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablepay-api-gateway
  namespace: stablepay-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
