package serial

import (
	"context"
	"fmt"
	"time"

	"code.wenfu.cn/stablepay/stablepay-common/id_generator/core"
)

// StandardConfig holds configuration for 32-digit Standard ID generation.
type StandardConfig struct {
	DataVer  string
	SysVer   string
	SysCode  string
	BizCode  string
	DC       string
	Env      string
	Reserved string
}

// Generator generates 32-digit Standard IDs.
type Generator struct {
	config    StandardConfig
	allocator *core.SegmentAllocator
}

// NewGenerator creates a new Standard ID generator.
func NewGenerator(config StandardConfig, allocator *core.SegmentAllocator) (*Generator, error) {
	if len(config.DataVer) != 1 {
		return nil, fmt.Errorf("DataVer must be 1 digit")
	}
	if len(config.SysVer) != 1 {
		return nil, fmt.Errorf("SysVer must be 1 digit")
	}
	if len(config.SysCode) != 3 {
		return nil, fmt.Errorf("SysCode must be 3 digits")
	}
	if len(config.BizCode) != 2 {
		return nil, fmt.Errorf("BizCode must be 2 digits")
	}
	if len(config.DC) != 2 {
		return nil, fmt.Errorf("DC must be 2 digits")
	}
	if len(config.Env) != 1 {
		return nil, fmt.Errorf("Env must be 1 digit")
	}
	if len(config.Reserved) != 2 {
		return nil, fmt.Errorf("Reserved must be 2 digits")
	}

	return &Generator{
		config:    config,
		allocator: allocator,
	}, nil
}

// Generate generates a 32-digit Standard ID.
// shardingKey should be a 16-character ID string generated by ident SDK,
// where positions 12-15 (1-indexed) contain the sharding information.
func (g *Generator) Generate(ctx context.Context, shardingKey string) (string, error) {
	// Validate shardingKey format
	if len(shardingKey) != 16 {
		return "", fmt.Errorf("shardingKey must be 16 characters, got %d", len(shardingKey))
	}

	// Extract positions 12-15 (1-indexed), which is indices 11-14 (0-indexed)
	// For a 16-char ID like "1234567891017388", this extracts "1738"
	shardingStr := shardingKey[11:15]

	// Validate sharding string contains only digits
	for _, c := range shardingStr {
		if c < '0' || c > '9' {
			return "", fmt.Errorf("sharding key contains non-numeric characters: %s", shardingStr)
		}
	}

	seq, err := g.allocator.NextId(ctx)
	if err != nil {
		return "", fmt.Errorf("failed to get sequence: %w", err)
	}
	seq = seq % 100000000 // 8 digits

	// Extract DB and table shards directly from string (preserves leading zeros)
	// First 2 digits = DB shard, last 2 digits = table shard
	dbShardStr := shardingStr[0:2]
	tbShardStr := shardingStr[2:4]

	dateStr := time.Now().Format("20060102")

	id := fmt.Sprintf("%s%s%s%s%s%s%s%s%s%s%08d",
		dateStr,
		g.config.DataVer,
		g.config.SysVer,
		g.config.SysCode,
		g.config.BizCode,
		g.config.DC,
		dbShardStr,
		tbShardStr,
		g.config.Env,
		g.config.Reserved,
		seq,
	)

	if len(id) != 32 {
		return "", fmt.Errorf("generated id length error: expected 32, got %d", len(id))
	}

	return id, nil
}
