apiVersion: v1
kind: Secret
metadata:
  name: stablepay-secrets
  namespace: stablepay-dev
type: Opaque
stringData:
  mysql-root-password: "root123"
  mysql-user: "stablepay"
  mysql-password: "stablepay123"
  # 请替换为真实 Solana 热钱包 JSON 内容
  hotwallet.json: |
    {
      "address": "FMNs7xqezz4bYYioPyfqPzxLLmZyJhjSzbGApMdnrC2Z",
      "did": "did:solana:FMNs7xqezz4bYYioPyfqPzxLLmZyJhjSzbGApMdnrC2Z",
      "public_key": "FMNs7xqezz4bYYioPyfqPzxLLmZyJhjSzbGApMdnrC2Z",
      "private_key": "3LiPaQYYmorCC3zFKdjfu1ie1e4WpcVN1GSYUo4wpHKBkf9TVL5noXurR5ersNRDvWtZQHcQS2kcA6rW4Ncukxgu",
      "role": "hot_wallet",
      "description": "DevNet 测试热钱包"
    }
