// Code generated by Kitex v0.16.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	payment_service "github.com/stablepay/api-gateway/kitex_gen/stablepay/payment_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InitiatePayment(ctx context.Context, req *payment_service.InitiatePaymentRequest, callOptions ...callopt.Option) (r *payment_service.InitiatePaymentResponse, err error)
	GetPaymentStatus(ctx context.Context, req *payment_service.GetPaymentStatusRequest, callOptions ...callopt.Option) (r *payment_service.GetPaymentStatusResponse, err error)
	ListPaymentHistory(ctx context.Context, req *payment_service.ListPaymentHistoryRequest, callOptions ...callopt.Option) (r *payment_service.ListPaymentHistoryResponse, err error)
	GetPaymentRequirement(ctx context.Context, req *payment_service.GetPaymentRequirementRequest, callOptions ...callopt.Option) (r *payment_service.GetPaymentRequirementResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) InitiatePayment(ctx context.Context, req *payment_service.InitiatePaymentRequest, callOptions ...callopt.Option) (r *payment_service.InitiatePaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitiatePayment(ctx, req)
}

func (p *kPaymentServiceClient) GetPaymentStatus(ctx context.Context, req *payment_service.GetPaymentStatusRequest, callOptions ...callopt.Option) (r *payment_service.GetPaymentStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPaymentStatus(ctx, req)
}

func (p *kPaymentServiceClient) ListPaymentHistory(ctx context.Context, req *payment_service.ListPaymentHistoryRequest, callOptions ...callopt.Option) (r *payment_service.ListPaymentHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPaymentHistory(ctx, req)
}

func (p *kPaymentServiceClient) GetPaymentRequirement(ctx context.Context, req *payment_service.GetPaymentRequirementRequest, callOptions ...callopt.Option) (r *payment_service.GetPaymentRequirementResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPaymentRequirement(ctx, req)
}
