// Code generated by Kitex v0.16.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	payment_service "github.com/stablepay/api-gateway/kitex_gen/stablepay/payment_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"InitiatePayment": kitex.NewMethodInfo(
		initiatePaymentHandler,
		newPaymentServiceInitiatePaymentArgs,
		newPaymentServiceInitiatePaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPaymentStatus": kitex.NewMethodInfo(
		getPaymentStatusHandler,
		newPaymentServiceGetPaymentStatusArgs,
		newPaymentServiceGetPaymentStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListPaymentHistory": kitex.NewMethodInfo(
		listPaymentHistoryHandler,
		newPaymentServiceListPaymentHistoryArgs,
		newPaymentServiceListPaymentHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPaymentRequirement": kitex.NewMethodInfo(
		getPaymentRequirementHandler,
		newPaymentServiceGetPaymentRequirementArgs,
		newPaymentServiceGetPaymentRequirementResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment_service.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func initiatePaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment_service.PaymentServiceInitiatePaymentArgs)
	realResult := result.(*payment_service.PaymentServiceInitiatePaymentResult)
	success, err := handler.(payment_service.PaymentService).InitiatePayment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceInitiatePaymentArgs() interface{} {
	return payment_service.NewPaymentServiceInitiatePaymentArgs()
}

func newPaymentServiceInitiatePaymentResult() interface{} {
	return payment_service.NewPaymentServiceInitiatePaymentResult()
}

func getPaymentStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment_service.PaymentServiceGetPaymentStatusArgs)
	realResult := result.(*payment_service.PaymentServiceGetPaymentStatusResult)
	success, err := handler.(payment_service.PaymentService).GetPaymentStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceGetPaymentStatusArgs() interface{} {
	return payment_service.NewPaymentServiceGetPaymentStatusArgs()
}

func newPaymentServiceGetPaymentStatusResult() interface{} {
	return payment_service.NewPaymentServiceGetPaymentStatusResult()
}

func listPaymentHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment_service.PaymentServiceListPaymentHistoryArgs)
	realResult := result.(*payment_service.PaymentServiceListPaymentHistoryResult)
	success, err := handler.(payment_service.PaymentService).ListPaymentHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceListPaymentHistoryArgs() interface{} {
	return payment_service.NewPaymentServiceListPaymentHistoryArgs()
}

func newPaymentServiceListPaymentHistoryResult() interface{} {
	return payment_service.NewPaymentServiceListPaymentHistoryResult()
}

func getPaymentRequirementHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment_service.PaymentServiceGetPaymentRequirementArgs)
	realResult := result.(*payment_service.PaymentServiceGetPaymentRequirementResult)
	success, err := handler.(payment_service.PaymentService).GetPaymentRequirement(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceGetPaymentRequirementArgs() interface{} {
	return payment_service.NewPaymentServiceGetPaymentRequirementArgs()
}

func newPaymentServiceGetPaymentRequirementResult() interface{} {
	return payment_service.NewPaymentServiceGetPaymentRequirementResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) InitiatePayment(ctx context.Context, req *payment_service.InitiatePaymentRequest) (r *payment_service.InitiatePaymentResponse, err error) {
	var _args payment_service.PaymentServiceInitiatePaymentArgs
	_args.Req = req
	var _result payment_service.PaymentServiceInitiatePaymentResult
	if err = p.c.Call(ctx, "InitiatePayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPaymentStatus(ctx context.Context, req *payment_service.GetPaymentStatusRequest) (r *payment_service.GetPaymentStatusResponse, err error) {
	var _args payment_service.PaymentServiceGetPaymentStatusArgs
	_args.Req = req
	var _result payment_service.PaymentServiceGetPaymentStatusResult
	if err = p.c.Call(ctx, "GetPaymentStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPaymentHistory(ctx context.Context, req *payment_service.ListPaymentHistoryRequest) (r *payment_service.ListPaymentHistoryResponse, err error) {
	var _args payment_service.PaymentServiceListPaymentHistoryArgs
	_args.Req = req
	var _result payment_service.PaymentServiceListPaymentHistoryResult
	if err = p.c.Call(ctx, "ListPaymentHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPaymentRequirement(ctx context.Context, req *payment_service.GetPaymentRequirementRequest) (r *payment_service.GetPaymentRequirementResponse, err error) {
	var _args payment_service.PaymentServiceGetPaymentRequirementArgs
	_args.Req = req
	var _result payment_service.PaymentServiceGetPaymentRequirementResult
	if err = p.c.Call(ctx, "GetPaymentRequirement", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
